### ISSUE TITLE
Incorporate `resources.txt` into the local repo and update the scriptlets

### ISSUE THREAD

**Issue by JustOff** [gorhill/uBlock-for-firefox-legacy#134]
Since `resources.txt` hosted on `uAssets` [has become obsolete](https://github.com/gorhill/uBlock/commit/6f5aa947fb3b2abdd112411f34995233b28f7bf9#commitcomment-34206609), it should be incorporated into the local repo. This will allow keeping the scriptlets in sync with the upstream [scriptlets.js](https://github.com/gorhill/uBlock/blob/master/assets/resources/scriptlets.js).

- [x] Incorporate [resources.txt](https://github.com/uBlockOrigin/uAssets/blob/master/filters/resources.txt) into the local repo
- [x] Add missing scriptlets
  - [x] [nosiif.js](https://github.com/gorhill/uBlock/wiki/Resources-Library#nosiifjs-) (`no-setInterval-if.js`)
  - [x] [nostif.js](https://github.com/gorhill/uBlock/wiki/Resources-Library#nostifjs-) (`no-setTimeout-if.js`)
  - [x] [raf-if.js](https://github.com/gorhill/uBlock/wiki/Resources-Library#raf-ifjs-) (`requestAnimationFrame-if.js`)
  - [x] [json-prune.js](https://github.com/gorhill/uBlock/wiki/Resources-Library#json-prunejs-)
- [x] Check and update [existing scriptlets](https://github.com/gorhill/uBlock/wiki/Resources-Library)
  - [x] [set-constant](https://github.com/gorhill/uBlock/commit/c7dc65fe33ed58ff2bad10ce4a8848b97c8591ce#diff-d7616deaf3a39e3f19f8d70d098bfe7a)
  - [x] [abort-current-inline-script](https://github.com/gorhill/uBlock/commit/1a8571755e43da75901ffec194a0dd30c8665b06#diff-d7616deaf3a39e3f19f8d70d098bfe7a)
- [x] Update [filter syntax converter](https://github.com/gorhill/uBlock-for-firefox-legacy/commit/eb44efc1fe515294d6fd188b6a49b4c2d3a346f9)
- [x] Force updating `resources.txt` when installing a new version
- [x] Force updating all filters when installing the next version

**Comment by JustOff** [comment]
@THEtomaso, if you have time, please test build [1.16.4.18b1](https://github.com/JustOff/uBlock-for-firefox-legacy/releases/tag/1.16.4.18b1). It includes all the new and updated scriptlets mentioned above, and the filter syntax converter updated accordingly.

**Comment by THEtomaso** [comment]
*Testing*

Convertion still seems to work just fine. :)
Although, I son't see **raf-if.js** actually being used anywhere.

**Comment by JustOff** [comment]
> Although, I don't see raf-if.js actually being used anywhere.

Try to enable `uBlock filters – Annoyances​​​​​​​​​` and visit bloomberg.com.

**Comment by THEtomaso** [comment]
Ah, there we go..
I'm already using that filter.
Convertion confirmed! :)

**Comment by JustOff** [comment]
> Convertion confirmed! :)

I wish I could verify the actual effect of `raf-if.js` there ... [Here](https://www.reddit.com/r/uBlockOrigin/comments/d8qeg8/bloomberg_detecting_incognito_mode/) is the initial report.

**Comment by THEtomaso** [comment]
Actually, it doesn't work.
The whole articles aren't shown in incognito / private browsing mode.
But the unconverted rule doesn't work with Chromium-ungoogled's incognito mode either, so Bloomberg has probably updated their nasties.

**Comment by JustOff** [comment]
@THEtomaso, are there any other observations or remarks?

**Comment by THEtomaso** [comment]
I ran your beta in a portable build, for about a day.
Didn't notice anything out of the ordinary.

**Comment by JustOff** [comment]
Thanks, I've also been successfully using it for two days now, so tomorrow I will most likely be preparing everything for release.
