### ISSUE TITLE
Add support for ":nth-ancestor" and ":upward"

### ISSUE THREAD

**Issue by DandelionSprout** [gorhill/uBlock-for-firefox-legacy#224]
While I haven't tested it in Pale Moon (nor SeaMonkey) myself, I think uBO added the new ":nth-ancestor" feature to the regular uBO versions sometime in the past year, and I'm already liking it enough that I'm predicting it'll become a major feature in uBO-specific lists within the next year or two.

So I presume that adding support for it would be advantageous for you guys.

**Comment by JustOff** [comment]
Wiki: [subject:nth-ancestor(n)](https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters#subjectnth-ancestorn)

Current usage:
```
cd ../uAssets/filters;  grep nth-ancestor * | wc -l
28
```

**Comment by krystian3w** [comment]
Some diffrence beetwen `kth-ancestor`?

**Comment by DandelionSprout** [comment]
One key difference is that `:kth-ancestor` with a K is not supported by *any* known version of uBO or Nano, I would presume.

As for the mathematical/coding difference, I'm not really sure. If anyone with a university math education can figure out [this article](https://wikidiff.com/kth/nth) or anything similar, that'd be more helpful than anything I could've said.

**Comment by THEtomaso** [comment]
**uBlock filters** already contains a bunch of rules, which uses `nth-ancestor`.
For the time being, perhaps it would be possible to add more code to the converter, thereby turning those rules into `xpath` syntaxes?

**Comment by JustOff** [comment]
> perhaps it would be possible to add more code to the converter

Someone can try, but it will not be me.

**Comment by THEtomaso** [comment]
Currently, the highest `nth-ancestor` n-value in **uBlock filters** is only 5.
I might be wrong, but wouldn't it simplify thing a lot, if you were to add 5 separate convertion rules, like this?
```
:nth-ancestor(1) = :xpath(..)
:nth-ancestor(2) = :xpath(../..)
:nth-ancestor(3) = :xpath(../../..)
:nth-ancestor(4) = :xpath(../../../..)
:nth-ancestor(5) = :xpath(../../../../..)
```
..or perhaps add a few more, to be on the safe side?:
```
:nth-ancestor(6) = :xpath(../../../../../..)
:nth-ancestor(7) = :xpath(../../../../../../..)
:nth-ancestor(8) = :xpath(../../../../../../../..)
:nth-ancestor(9) = :xpath(../../../../../../../../..)
```

**Comment by JustOff** [comment]
Well, you can play around with it: [uBlock0_1.16.4.19b1.firefox-legacy.xpi.zip](https://github.com/gorhill/uBlock-for-firefox-legacy/files/4241677/uBlock0_1.16.4.19b1.firefox-legacy.xpi.zip) (rename to xpi).

**Comment by THEtomaso** [comment]
Don't know much about this stuff, I'm afraid.
I've edited XPI files before, but only to apply hacks of the most brutal kind! :)

**Comment by DandelionSprout** [comment]
I remember experimenting with the uBO XPI once before to try to copy over entire files from the regular branch, which didn't go so well (It didn't take much changes for the entire extension to cease working entirely), but I presume JustOff intended for the changes to be made to the one single same file that the `##+js` conversions were added to?

I could've plausibly done it myself, but I've had a pretty tiring day today.

**Comment by JustOff** [comment]
> Don't know much about this stuff, I'm afraid.

I gave you already patched xpi with your rules added.

**Comment by THEtomaso** [comment]
Ah, so that's what it was.
I'll give it a try! :)

**Comment by THEtomaso** [comment]
Seems to work just fine! :+1:

**Comment by JustOff** [comment]
Yes, 9, and we can use this as a workaround, right?

**Comment by THEtomaso** [comment]
Yes, all rules looks to have been converted correctly, and I saw them being applied in the logger too.
Although, I couldn't exactly pinpoint their effects.

**Comment by JustOff** [comment]
Well, @DandelionSprout, @krystian3w, what do you think about this workaround? Is it correct and worth including to the next uBO-legacy release?

**Comment by DandelionSprout** [comment]
After 15min of setting up a test setup, it seems that `tek.no##div[id$=_body_ad]:nth-ancestor(1)` in my Nordic list was converted to `tek.no##div[id$=_body_ad]:xpath(..)`, which successfully removes a few small ad placeholders at `https://www.tek.no/nyheter/nyhet/i/Wb1ela/derfor-fikk-mange-1-tall-pa-mobilen-torsdag`.

So my personal standpoint is that the workaround actually works, if that accounts for anything. So I presume it's includable.

**Comment by JustOff** [comment]
Thanks everyone for testing, I pushed this workaround to the master for the next release.

**Comment by DandelionSprout** [comment]
Additionally, is there any particular reason why the conversion is even limited to specified lists to begin with?

One thing is accidentally excluding My Filters, but as it currently stands the script is skipping Frellwit's Swedish Filter, Adblock List for Finland, uAssets Resource Abuse, and probably a couple dozen other lists out there (incl. ones not included in uBO) that have at least one affected list entry.

**Comment by THEtomaso** [comment]
> One thing is accidentally excluding My Filters

The converter should NOT interfere with "My filters"!
People that use uBO Legacy should make sure that the rules that they create themselves are legacy-compatible.
I, for one, does NOT want an automated process to "correct" any of my own rules!
I don't see a reason to exclude ANY filters under "Filter lists" though.

**Comment by JustOff** [comment]
@gwarser, @DandelionSprout, @THEtomaso
Let's continue the discussion about filter syntax converter in [this separate issue](https://github.com/gorhill/uBlock-for-firefox-legacy/issues/228).

**Comment by uBlock-user** [comment]
:nth-ancestor will be deprecated for :upward  soon -- https://github.com/gorhill/uBlock/commit/72bb70056843024b1a31fe1ab9c90bd4e8260ba2

**Comment by JustOff** [comment]
Thank you for letting us know about this. This will probably lead to a new workaround, unless of course someone smarter joins the uBO-legacy improvement to add support for new operators properly.

**Comment by smnthermes** [comment]
How about rebasing on some Firefox release?

**Comment by JustOff** [comment]
Since #240, among other things, introduces native support of `:nth-ancestor(n)`, here is another test version, where I removed mapping of `:nth-ancestor(n)` to `:xpath(..)` from the syntax converter and also changed mapping of `:upward(n)` from `:xpath(..)` to `:nth-ancestor(n)`:

```js
        ':upward(1)': ':nth-ancestor(1)',
        ':upward(2)': ':nth-ancestor(2)',
        ':upward(3)': ':nth-ancestor(3)',
        ':upward(4)': ':nth-ancestor(4)',
        ':upward(5)': ':nth-ancestor(5)',
        ':upward(6)': ':nth-ancestor(6)',
        ':upward(7)': ':nth-ancestor(7)',
        ':upward(8)': ':nth-ancestor(8)',
        ':upward(9)': ':nth-ancestor(9)'
```
[uBlock0_1.16.4.23b2.firefox-legacy.xpi.zip](https://github.com/gorhill/uBlock-for-firefox-legacy/files/4874654/uBlock0_1.16.4.23b2.firefox-legacy.xpi.zip)

**Comment by JustOff** [comment]
@THEtomaso
Could you please take a look at [uBlock0_1.16.4.24b2.firefox-legacy.xpi.zip](https://github.com/gorhill/uBlock-for-firefox-legacy/files/4938056/uBlock0_1.16.4.24b2.firefox-legacy.xpi.zip) based on PR #252 which introduces full native support of `:upward` and also implements `:remove`.

**Comment by THEtomaso** [comment]
One thing that I noticed right away, is that the `:upward` rules are completely messed up in uBO's logger!

Example:
**Dandelion Sprout's Nordic filters** contains this rule:
`730.no##.gofollow:upward(3)`

But when opening `730.no`, this is shown in the logger:
`####.gofollow:upward(3)`
(4 number signs)

Also, when clicking on a `:upward` entry in the logger, it doesn't show which filter the rule originates from.
Instead, it simply shows a blank window!

**Comment by JustOff** [comment]
Please try [uBlock0_1.16.4.24b3.firefox-legacy.xpi.zip](https://github.com/gorhill/uBlock-for-firefox-legacy/files/4938951/uBlock0_1.16.4.24b3.firefox-legacy.xpi.zip)

**Comment by THEtomaso** [comment]
Well, that seems to have fixed the logger issue for `:upward` rules.

But now, `:remove` rules doesn't show up in the logger at all!
Example:
`navi.z0i.net##.adsbygoogle:remove()` @ `http://navi.z0i.net/`

**Comment by JustOff** [comment]
[uBlock0_1.16.4.24b4.firefox-legacy.xpi.zip](https://github.com/gorhill/uBlock-for-firefox-legacy/files/4939160/uBlock0_1.16.4.24b4.firefox-legacy.xpi.zip) ?

**Comment by THEtomaso** [comment]
Yes, that did the trick! :+1: 
Now, if I only could figure out what those extremely rare `:remove` rules does, perhaps we would be able to confirm that the rules actually works too. :)

**Comment by JustOff** [comment]
> Yes, that did the trick!

Thanks for the confirmation!

> if I only could figure out what those extremely rare :remove rules does

I can confirm it works, you can try this one:
```
youtube.com##[page-subtype="channels"] > #contents #player-container:remove()
```
and open any YT channel, f.e. https://www.youtube.com/user/NationalGeographic

**Comment by THEtomaso** [comment]
Indeed, it works!
As usual; many thanks to the both of you, hawkeye116477 and JustOff! :+1:

**Comment by THEtomaso** [comment]
@hawkeye116477:
Is this fix directly appliable for the Legacy branch?:
https://github.com/gorhill/uBlock/commit/7dd48a6c8c4d9153b4bc3f56904f3abfb5b23512
