### ISSUE TITLE
Getting static ad before youtube video

### ISSUE THREAD

**Issue by nhantrn** [gorhill/uBlock-for-firefox-legacy#226]
This happened maybe a few times couple of weeks ago and haven't reoccur since until today. Now youtube will show ads and leave a `dkv` cookie. Subsequent videos  then will not have ads. But if I clear that cookie, then a new static ads will appear. This is on a windows 10 and firefox 52esr.

see:
![2020-02-28_165756](https://user-images.githubusercontent.com/3202654/75598172-b57f5480-5a91-11ea-9533-a62b85637c6c.jpg)

Edit: Uh oh. I just got one in chrome too. Though it didn't reappear after clearing cookies. Can anyone double check? paging @gorhill

Edit2: Hmm. If I open it in private/incognito mode, it doesn't show ads so far. I have my regular tab logged into youtube.

**Comment by JustOff** [comment]
> I just got one in chrome too. 

Filter issues must be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
