### ISSUE TITLE
Revise the scope of the filter syntax converter

### ISSUE THREAD

**Issue by JustOff** [gorhill/uBlock-for-firefox-legacy#228]
Currently, [filter syntax converter](https://github.com/gorhill/uBlock-for-firefox-legacy/commit/eb44efc1fe515294d6fd188b6a49b4c2d3a346f9) applies only to an explicitly specified limited set of filters, and also does not apply to "My filters".

There was a [request](https://github.com/gorhill/uBlock-for-firefox-legacy/issues/224#issuecomment-595491522) that this behavior needs to be adjusted.

**Comment by JustOff** [comment]
> is there any particular reason why the conversion is even limited to specified lists

This was done for performance reasons. This was discussed in more detail somewhere deep in [General filter chit-chat](https://github.com/DandelionSprout/adfilt/issues/7), but its size does not allow me now to find exactly where it was. The current list was created based on which of the filters uses the new syntax. We can expand it if I missed something or think of an additional advanced option to enable processing of all filters, but I would not want to enable it by default.

**Comment by THEtomaso** [comment]
I agree that all filters should be converted, including "user filters" (if you refer to "custom" ones, under uBO's "**Filter lists**" tab).
However, anything that exist under "**My filters**" should be left alone!

**Comment by JustOff** [comment]
> This translation is not applied to "My filters"?

Yes, and this was done intentionally so as not to confuse users. Filters loaded from remote sources are displayed by uBO already converted and are displayed in the logs in the same way. With custom filters this will not work, so they are not converted, and displayed and used as is. Theoretically, I can try to add an additional option that will activate the converter for user filters, if you need it for A/B testing, but I'm afraid that you yourself will get confused.

**Comment by DandelionSprout** [comment]
>The current set of filters to proceed was created based on which of the filters uses the new syntax. We can expand it if I missed something (…)

That approach has the disadvantage that it doesn't automatically account for whenever a new list has moved from the old syntax to the new. For instance, Frellwit's list now has ≥100 entries with the new +js syntax, which I think happened after the inital creation of the conversion script.

**Comment by JustOff** [comment]
`+js syntax` is supported by uBO legacy and don't need a converter.

**Comment by DandelionSprout** [comment]
Frellwit's list used the old syntax when the conversion began, but has since moved on to the new syntax.

For instance, in uBO 1.16.4.19 on Pale Moon 18.8.4 64-bit, testing on `https://www.vasterastidning.se/`, the following entries from lines 2774-2777 (preceded by some dozen domains):

```
##+js(set, youplay.helpers.getTrackUrl, noopFunc)
##+js(set, youplay.helpers.disableRightClick, noopFunc)
##+js(set, youplay.helpers.getTrackUrl, noopFunc)
##+js(set, youplay.helpers.trackUrls, noopFunc)
```

...are not shown in the uBO logger as having been applied.

**Comment by THEtomaso** [comment]
Yes, **Frellwit's Swedish Filter** does indeed use the new filter syntaxes, and so does many other filters, which the converter currently doesn't process!

**Comment by JustOff** [comment]
Ok, probably then it's worth adding all regional filters to the list for processing by default. However, turning processing on globally will have too much negative impact on performance due to monsters like EasyList or Malware Domains, which are also just pointless to process, just like all AdGuard lists.

**Comment by THEtomaso** [comment]
What about the custom filters?
I'm, currently using 12 myself, and I know some people that use even more!

**Comment by JustOff** [comment]
> What about the custom filters?

What about an option in the advanced settings to turn on global processing? Unfortunately, the best solution has not yet crossed my mind.

> How much of a performance drop do you estimate

This can cause the browser to freeze for several seconds when updating filters.

**Comment by DandelionSprout** [comment]
Trying to rule out lists that quite clearly intended to target ABP only (e.g. Greek Adblock Filter, EasyList Italy, etc.), gave me these results:

```
* All uAssets lists
* CJX's EasyList Lite
* EasyList Czech and Slovak
* Adblock List for Finland
* EasyList Hebrew
* Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
* Frellwit's Swedish Filters
* EasyList Thailand
```

It's also possible that AdGuard, who are *themselves* already converting from their own `#%#AG_` and/or `#%#//scriptlet` into uBO's old syntax, may choose to convert into the new syntax instead. If that day comes, *all* AdGuard lists would have to be whitelisted at the same time.

**Comment by THEtomaso** [comment]
> This can cause the browser to freeze for several seconds when updating filters.

OK, an optional advanced setting sounds like a reasonable solution then.
This will enable processing for custom filters too, right?

**Comment by krystian3w** [comment]
https://github.com/gorhill/uBlock-for-firefox-legacy/issues/224#issuecomment-596205189

> 
> 
> FYI :nth-ancestor will be deprecated for :upward soon -- [gorhill/uBlock@72bb700](https://github.com/gorhill/uBlock/commit/72bb70056843024b1a31fe1ab9c90bd4e8260ba2)

**Comment by THEtomaso** [comment]
> What about an option in the advanced settings to turn on global processing?

Or something like this, perhaps?:

![ublockorigin-possiblefunction](https://user-images.githubusercontent.com/9382674/76165943-4671c200-615b-11ea-8289-be2a4fb105d7.jpg)

**Comment by JustOff** [comment]
Well, it seems that since the initial implementation of the filter syntax converter, my test results for its performance are somewhat outdated. I checked it again and it turned out that now it looks quite good at handling even large filters like EasyList or Malware Domains.

Here is a test version that has `assetConvertAllRemote` parameter in the advanced settings:

[uBlock0_1.16.4.20b2.firefox-legacy.xpi.zip](https://github.com/gorhill/uBlock-for-firefox-legacy/files/4333240/uBlock0_1.16.4.20b2.firefox-legacy.xpi.zip) (rename to xpi)

Could you please check how uBO behaves when this option turned on in your case? Perhaps now we can just apply the converter for all filters (except My Filters)?

There is also `assetConvertMyFilters` parameter, you can play around with it too if you want.

**Comment by THEtomaso** [comment]
@JustOff:

Thanks.

Unfortunatley, your latest beta build (v1.16.4.20b2) struggles with custom filters.
Even with those new advanced parameters disabled, all custom filters take a long time to update, and **I don't care about cookies** completely fails!

Steps to reproduce:
1 - Add **I don't care about cookie**s to your custom filters: `https://www.i-dont-care-about-cookies.eu/abp/`
2 - Try to update it!
- Expected result: The filter should update itself.
- Actual result: The update process fails!

**Comment by JustOff** [comment]
> https://www.i-dont-care-about-cookies.eu/abp/

It seems it simply does not respond at all at the moment.

**Comment by THEtomaso** [comment]
@JustOff:
See the edit in my previous post!

**Comment by JustOff** [comment]
Sorry, but your guess is most likely irrelevant. If something is timed out that no one can load it)

**Comment by krystian3w** [comment]
`gorhill/uBlock@703c525` no copied too legacy, IMO also no exist in beta legacy XPI.

**Comment by THEtomaso** [comment]
> no copied to legacy

Hmm, I though this was processed online?

This seems relevant enough to me:

> I verified and could not find any instance in major
> filter lists of lines ending with ` \`, thus the
> change should be safe.

Of course, **I don't care about cookies** ends with `/`, rather than `\`, but the change was added today, and now suddenly **I don't care about cookies** fails to update itself!?

**Comment by krystian3w** [comment]
My point is that Kiboke has an overloaded web server and the browser displays the list as a text document in 3 minutes.

**Comment by JustOff** [comment]
> Of course, I don't care about cookies ends with /, rather than \

Sorry, but you also don't get the essence of the https://github.com/gorhill/uBlock/commit/703c525b01aa3fb9dab94d6a9918a0a69c6d18da, it's about the filter content, not the address.

> now suddenly I don't care about cookies fails to update itself!

Just try to open it in browser. Coincidences happen :smile:

**Comment by THEtomaso** [comment]
It opens just fine in my browser, but still fails in uBO!

**Comment by krystian3w** [comment]
Try in private tab / window open, maybe Nordic region have magic CDN-s...

**Comment by JustOff** [comment]
Please, calm down a little. www.i-dont-care-about-cookies.eu is having problems right now. The browser gets cached response from Cloudflare after 90 sec timeout, while uBO doesn't wait more then 60 sec. You can also check the mainstream uBO in Firefox or Chrome.

**Comment by THEtomaso** [comment]
I'm calm. :)
It's weird though..
The list opens instantly for me, every single time, both in Pale Moon and in Chromium-ungoogled, but fails every single time in uBO!

**Comment by THEtomaso** [comment]
I've mirrored IDCAC on my own server.
I'll have uBO fetching it from there for now, and go back to testing v1.16.4.20b2! :)

**Comment by THEtomaso** [comment]
OK, all filters (including custom ones) are updating just fine now.
Both of the new advanced parameters seems to work like intended, and the converted rules are applied to sites correctly!
Great work again, JustOff!! :+1:

**Comment by JustOff** [comment]
Thanks, but what can you say about browser / CPU load when updating all filters? I tend to consider it acceptable and enable the converter for all filters (except My Filters) without any options.

**Comment by THEtomaso** [comment]
I didn't exactly monitor it, but if there was a difference when updating, it sure wasn't noticable at my end.
I've never used the auto-update option though, so I wouldn't even know if that particular function has a noticable effect when browsing, under normal circumstances.

**Comment by JustOff** [comment]
I rethought it all over and decided to make filter syntax converter process all filters except explicitly excluded.

I am going to exclude only the following filters, which currently do not change after applying the converter:

- Adblock Warning Removal
- EasyList
- AdGuard Tracking Protection
- EasyPrivacy
- Malvertising filter list by Disconnect
- Malware Domain List
- Malware domains
- Spam404
- AdGuard Social Media
- Anti-Facebook
- Fanboy’s Annoyance
- EasyList Cookie
- Fanboy’s Social
- Dan Pollock’s hosts file
- hpHosts’ Ad and tracking servers
- MVPS HOSTS
- Peter Lowe’s Ad and tracking server list

There will also be an advanced option `assetConvertMyFilters` to make the converter process `My Filters` (disabled by default).

**Comment by THEtomaso** [comment]
Sounds good!
Although, why not leave the `assetConvertAllRemote` option in there too?
I mean, since you've already created it.
It won't affect performance, as long as it's disabled by default anyway! :)

**Comment by JustOff** [comment]
I carefully checked the filters that I'm going to exclude and I think that the probability that some of them in the future may require conversion is quite small. However, if this does happen, I would prefer it to be reported and corrected for everyone, rather than for only the one who discovered it.

**Comment by THEtomaso** [comment]
Fair enough.
Really, the only problem I can forsee is if the AdGuard team suddenly decides to change their syntaxes too, like gorhill has done.

**Comment by JustOff** [comment]
In fact, AdGuard filters already use syntax that requires conversion and such filters are not excluded (Adblock Warning Removal, AdGuard Base, AdGuard Mobile Ads, etc.). At the same time, [AdGuard Tracking Protection](https://filters.adtidy.org/extension/ublock/filters/3.txt) and [AdGuard Social Media](https://filters.adtidy.org/extension/ublock/filters/4.txt), which are excluded, seem to use only simple syntax by the very nature of these filters. Though, if I'm wrong, this can always be corrected later.

**Comment by krystian3w** [comment]
AG no needed, They recently launched (a month ago?) `xpath` and `nth-ancestor` (I don't think they've started turning it into a `upward()` one yet).

In addition, when it comes to scriptlets, they have already made sure that long names are used instead of abbreviated ones.

**Comment by THEtomaso** [comment]
Well, let's just ask the source..

@BlazDT:
Can you confirm that there are no immediate plans to change filter syntaxes in '**AdGuard Social Media filter**' and '**AdGuard Tracking Protection filter**'?

**Comment by BlazDT** [comment]
At least not that I am aware of. We rarely use javascript rules in Tracking and Social filter.

@ameshkov Or is anything planned I am probably not aware of (at least not found anything in filters chat)?

**Comment by ameshkov** [comment]
@DandelionSprout 
> converting from their own #%#AG_ and/or #%#//scriptlet into uBO's old syntax

Wait-wait-wait, what have I missed, the scriptlets syntax was changed again?

Regarding the question original:

> Really, the only problem I can foresee is if the AdGuard team suddenly decides to change their syntaxes too, like gorhill has done.

I wholeheartedly hate backward-incompatible syntax changes that appear out of the blue.

**Comment by JustOff** [comment]
`uBO` itself perfectly understands both the new and old syntax, but `uBO-filters` [have been converted](https://github.com/DandelionSprout/adfilt/issues/7#issuecomment-572937742) to the new shorthand one. That is why `uBO-legacy` now has [filter syntax converter](https://github.com/gorhill/uBlock-for-firefox-legacy/blob/128a34810f544504c0eb7b66558e8055967f23b2/src/js/assets.js#L294-L386), and here we discuss which filters from other sources also require it to be applied.

**Comment by DandelionSprout** [comment]
The change occured 1~2 years ago, so that e.g. `abort-on-property-read.js` could now be written as `aopr`. But it was only gradually introduced to the uAssets lists this winter.

Double-checking with my *AdGuard for Windows* installation, `aopr` is already converted into `#%#//scriptlet('ubo-acis.js'`; at least for those lists that are included in that extension such as my Nordic list.

**Comment by krystian3w** [comment]
But it's not about "uBo-Firefox-legacy", how AG convert the short names in AG-extension to works as an adguard scriplet filter.

If your record doesn't work:
`#%#//scriptlet('ubo-aopr.js';`

then report it converted to a long name:
`#%#//scriptlet('ubo-abort-on-property-read.js';`

 or add anchors in the code (alias).

**Comment by gwarser** [comment]
Scriptlet for Twitch does not work because filter does not have `.js` ?

**Comment by JustOff** [comment]
@gwarser, sorry, but I didn't quite understand your question.

**Comment by krystian3w** [comment]
He asks - "`uBO FX Legacy` is running the filter from uBlock list correctly?"

```
! https://github.com/uBlockOrigin/uAssets/issues/719
twitch.tv##+js(twitch-videoad)
```

I do not rule out the possibility that some of the advertisements are leaking, because the `uBO for FX Legacy` did not get an updated version of the script.

**Comment by gwarser** [comment]
One user on Reddit complained about ads on Twitch on Waterfox classic (or even older version). I tried adding custom scriptlet to uBO by advanced `userResourcesLocation`, but `twitch.tv##+js(twitch-videoad)` was not logged at all. Adding `twitch.tv##+js(twitch-videoad.js)` to My filters make it work.

**Comment by krystian3w** [comment]
"`My filters`" need use `.js`.

**Comment by gwarser** [comment]
Twitch scriptlet is not translated internally: https://github.com/gorhill/uBlock-for-firefox-legacy/blob/2a285b88be636b5a162c2465b7ea887e810d02bb/src/js/assets.js#L293

**Comment by krystian3w** [comment]
#284

**Comment by gwarser** [comment]
`twitch-videoad.js` is no longer used in uBO. Even specialized add-on is now failing. They fight hard.

**Comment by JustOff** [comment]
That's sad, but thanks for the info, since I don't use twitch myself and don't really follow this topic.

**Comment by krystian3w** [comment]
Rather, the script will not survive in this form anyway.

Also, it is unlikely to be supported by parameters so as not to update it "every 2 days" at extension code level.

**Comment by THEtomaso** [comment]
Well, I've been considering adding `||twitch.tv^$all` anyway..

**Comment by AroKol78** [comment]
```
https://www.chess.com/pl/tv/schedule
https://www.twitch.tv/dawidczerw
```

**Comment by krystian3w** [comment]
Yes, I have pre-roll ad (~15 sec).
