### ISSUE TITLE
"$all" and "$doc" currently don't seem to be supported

### ISSUE THREAD

**Issue by DandelionSprout** [gorhill/uBlock-for-firefox-legacy#229]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin (1.16.4.19 stable)
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Currently, neither `$all` or `$doc` seem to be supported by Firefox Legacy, as any strict blocking prompts don't show up.

Fixing `$doc` would be as simple as adding `'doc': 'main_frame'` to https://github.com/gorhill/uBlock-for-firefox-legacy/blob/755a8e0047d2d81c6bf5d30178be3437e7654ee5/src/js/static-net-filtering.js#L1379-L1409; but `$all` would possibly have to be converted into two different entries at once, one for nothing at all and one for `$popup`. Arguably even a third one for `$document` would have to be added, leading to complexity that makes me wonder if it's more ideal to just add native support for `$all` instead.

### A specific URL where the issue occurs

Just about anywhere on the internet, but let's assume `https://www.nrk.no/` as a very, very safe test site for this.

### Steps to Reproduce

1. Add `||nrk.no^$all` and `||nrk.no^$doc` to My Filters.
2. Visit `https://www.nrk.no/`.
3. See that the strict warning page doesn't show up, and that the site is loaded normally.

### Expected behavior:

The strict blocking page shows up. 
![image](https://user-images.githubusercontent.com/22780683/76142665-0b469480-6070-11ea-9564-c58a65e06abf.png)

### Actual behavior:

The page is loaded normally. 
![image](https://user-images.githubusercontent.com/22780683/76142636-d89c9c00-606f-11ea-87fa-538d468163e0.png)

### Your environment

* uBlock Origin version: 1.16.4.19
* Browser Name and version: Pale Moon 28.8.4 64-bit
* Operating System and version: Windows 10 November 2019 Update

**Comment by JustOff** [comment]
Could you please point me to the wiki or smth about `$all` keyword?

**Comment by JustOff** [comment]
Here is the test version - [uBlock0_1.16.4.20b1.firefox-legacy.xpi.zip](https://github.com/gorhill/uBlock-for-firefox-legacy/files/4324508/uBlock0_1.16.4.20b1.firefox-legacy.xpi.zip) (rename zip to xpi).


What is the best way to test `$all` operator?

**Comment by DandelionSprout** [comment]
I can confirm that `$doc` works as it should in 1.16.4.20b1, especially since force-updating my Nordic list in that version bumped the amount of entries in uBO's settings from ~900 to ~1,130.

I simply use `nrk.no` as my test site of choice for just about everything ever, as it has zero ads, ≤5 trackers, no region-locking (except for sports videos), and has a modern GUI. Although that site has no pop-up elements to test for whether `$all` covers `$popup`, I can confirm that `$all` covers just about everything else (incl `$document`), so I feel very certain that it also covers `$popup` as well.

**Comment by JustOff** [comment]
Thanks, I will put this beta in my main browser and watch how it behaves.

@THEtomaso, you may be interested in this as well.

**Comment by THEtomaso** [comment]
Thanks, JustOff.
I can also confirm that `$all` and `$doc` works in your latest beta (`$all` successfully covering `$document` and `$popup`)! :+1:

**Comment by DandelionSprout** [comment]
Having only now noticed that edit, I can confirm that `google.com/*/ChromeSetup.exe$all` does indeed simply close the Chrome download site tab when trying to download it. [👍/😅]

**Comment by THEtomaso** [comment]
### Issue:
While troubleshooting this problem, I think I might have discovered a bug related to uBO Legacy's `$all` implementation:
https://github.com/wolfbeast/lunarblocklist/issues/6/

How to reproduce (using uBO Legacy in Pale Moon):
1 - Add this blocking rule to your filters (found in 'Lunar Blocklist by Moonchild'):
`||pixel.`

2 - Open this page, and observe as all article images are blocked:
`https://www.thecut.com/2016/08/winona-ryder-c-v-r.html`

3 - Add this whitelisting rule:
`@@||pixel.nymag.com/imgs/$document,image`

4 - Reload the page, and observe as all article images are now shown.

5 - Now, right-click on one of the images, and select "View Image"..
The direct-linked image is now blocked!

6 - Add this whitelisting rule:
`@@||pixel.nymag.com/imgs/$all`

7 - Right-click on one of the images, and select "View Image" again..
The direct-linked image is now shown, while uBO's logger clearly states that it's allowed by the `$doc` variable.
So, why doesn't `$document` work?

**Comment by JustOff** [comment]
The above problem also occurs with uBO-legacy 1.16.4.19, i.e. before `all` and `doc` filter options were added, so please fill a separate issue for this.

PS: I would not advise you to use Lunar Blocklist with uBlock, just saying.

**Comment by THEtomaso** [comment]
> The above problem also occurs with uBO-legacy 1.16.4.19, i.e. before `all` and `doc` filter options were added

OK, good thing that we can rule that out then.
Thanks for troubleshooting! :)

--

> I would not advise you to use Lunar Blocklist with uBlock
Why not?
If I didn't, then who else would be filing issue reports for it? :)

--

btw; when testing this particular issue in other browsers, I discoverd yet again how flawed and potentially unsafe Chromium is.
The `$doc` / `$document` syntax aren't even needed for for Chromium, in this regard, as it somehow seems to convert the subdomain from `pixel.nymag.com` to `pyxis.nymag.com` natively, before uBO ever gets a chance to block it!

**Comment by gwarser** [comment]
> The `$doc` / `$document` syntax aren't even needed for Chromium, in this regard, as it somehow seems to convert the subdomain from `pixel.nymag.com` to `pyxis.nymag.com` natively, before uBO ever gets a chance to block it!

`pixel.nymag.com` returns 301 moved permanently, so it may be understandable to "optimize" by requesting directly `pyxis.nymag.com` when resource is requested next time.

**Comment by THEtomaso** [comment]
> "optimize"

Yeah, those quotation marks should indeed be included.
I've noticed a lot of that going on in Chromium, and I'm definitely not a fan of it!

**Comment by gwarser** [comment]
For 301 this is in specification.

**Comment by THEtomaso** [comment]
> For 301 this is in specification.

Of course, Pale Moon also redirects from `pixel.nymag.com` to `pyxis.nymag.com`.
But in this case, the redirection doesn't occur until after uBO has had a chance to block the original URL.
Browsers shouldn't assume anything, but rather threat any website like it's visiting it for the first time!

**Comment by THEtomaso** [comment]
@gwarser:
I stand corrected!:
https://github.com/gorhill/uBlock-for-firefox-legacy/issues/237#issuecomment-647176053
:blush:
