### ISSUE TITLE
Build 1.16.4.20 causes overheating issues in Waterfox Classic

### ISSUE THREAD

**Issue by Telmesomething** [gorhill/uBlock-for-firefox-legacy#231]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Encountered blocking issues as described in [this link](https://github.com/uBlockOrigin/uBlock-issues/issues/1020#) and subsequently installed build 1.16.4.20 as recommended. However the build causes my system to overheat. Have removed it now and reinstalled 1.26.2 which runs without a problem. The Zapper fails to work on later builds i.e. 1.27.2 and beyond.

### A specific URL where the issue occurs

https://www.theguardian.com/international

### Steps to Reproduce

1. System heats up after a few minutes of running the browser.
2. After about ten minutes the machine is considerably hotter and never cools down while the browser is open. 

### Expected behavior:

Build should not cause the system to overheat. 

### Actual behavior:

Machine runs too hot. 

### Your environment

* uBlock Origin version: 1.16.4.20
* Browser Name and version: Waterfox Classic 2020.5
* Operating System and version: Windows 8.1

**Comment by gwarser** [comment]
>Speculated performance issues will be marked as invalid and closed if they do not come with actual profiling data + analysis supporting the claim

http://profiler.firefox.com/ does not work on Waterfox :/ Even DevTools profiler does not work for me, WTF?

Do you see higher CPU usage? 

Is this with default filters?

**Comment by JustOff** [comment]
The prerequisites are not fulfilled, the issue is not reproduced.
