### ISSUE TITLE
v1.16.4.21?

### ISSUE THREAD

**Issue by THEtomaso** [gorhill/uBlock-for-firefox-legacy#232]
Might just as well release it with the current changes, don't you think?

**Comment by JustOff** [comment]
No, the current changes are definitely not worth the new release.

However, there are several significant updates that need to be ported from the mainstream, but unfortunately I have to postpone this task for some more time for personal reasons.

**Comment by JustOff** [comment]
Here is the list of changes for the upcoming 1.16.4.21 release:

- Prevent exceptions when several conflicting rules result in an empty filter
- Improve validation of CSS selector-based cosmetic filters
- Map `upward` to `xpath` using filter syntax converter
- Update scriptlets from the upstream repo
  - Replace `requestAnimationFrame-if.js` with `no-requestAnimationFrame-if.js`
  - Improve `set-constant.js` scriptlet
  - Improve `window.open-defuser` scriptlet
  - Add `remove-class` scriptlet (alias: `rc`)
  - Add new scriptlet to allow blocking Amazon's apstag.js
  - Bring `fingerprint2.js` scriptlet up to date
  - Improve logging capabilities of `json-prune` scriptlet
  - Add `uBO:` prefix to logged output in some scriptlets

You can try [uBlock0_1.16.4.21b3.firefox-legacy.xpi.zip](https://github.com/gorhill/uBlock-for-firefox-legacy/files/4804626/uBlock0_1.16.4.21b3.firefox-legacy.xpi.zip) (rename to xpi), feedback is highly appreciated.

**Comment by THEtomaso** [comment]
> feedback is highly appreciated

Works fine.
No issues, so far! :+1: 

BTW, JustOff..
What's your thoughts on this?:
https://github.com/gorhill/uBlock-for-firefox-legacy/issues/236/
I was kinda hoping that porting it would be more or less a straight copy/paste job, until I noticed you applying the "help wanted" label.
The change is already included in gorhill's beta branch, so it will be in the next stable build too.
In worst case, they'll start changing the existing rules in uBO filters right away..
Needless to say, this will be very, very bad for uBO Legacy, and no doubt its worst blow yet!

**Comment by JustOff** [comment]
I'm afraid I have to disappoint you, but there was too much refactoring in `staticNetFilteringEngine` module, so direct porting of https://github.com/gorhill/uBlock/commit/3c67d2b89f8ac6d680e74af3e11b916889f7 is not possible.

**Comment by THEtomaso** [comment]
@okiehsch:
If you're aware of the current plans, perhaps you could let us in on them?
Will a mass-convertion of uBO filters take place, to take advantage of entity-matching in `domain=` rules, once the next stable uBO release has been pushed out?

**Comment by okiehsch** [comment]
>a mass-conversion of uBO filters...  once the next stable uBO release has been pushed out?

No, it will take a while before we convert any existing filters. 
For example after the shorthand syntax change reached stable we waited months before converting existing filters.

**Comment by THEtomaso** [comment]
Thanks for the info, okiehsch.
At least, that is somewhat reassuring.
When the time comes.. if you remember, would you please give us a heads up, if this issue is still open at that point?:
https://github.com/gorhill/uBlock-for-firefox-legacy/issues/236/

btw, JustOff; You should probably add a "**Critical**" label to that issue too!
