### ISSUE TITLE
Omitting `.js` in scriptlet names

### ISSUE THREAD

**Issue by hawkeye116477** [gorhill/uBlock-for-firefox-legacy#235]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

On uBO web-ext I can do for example `belvederehotel.pl##+js(abort-on-property-read, pf_queen.push)`, so I can omit `.js` from scriptlet name, but seems that doesn't work with uBO Legacy.

**Comment by JustOff** [comment]
This is a known limitation of uBO legacy that skipping `.js` for long scriptlet names does not work you can only use the following options:

```
belvederehotel.pl##+js(abort-on-property-read.js, pf_queen.push)
belvederehotel.pl##+js(aopr.js, pf_queen.push)
belvederehotel.pl##+js(aopr, pf_queen.push)
```

These, however, cover all the syntaxes currently used in native uBO subscriptions, and I'm inclined to wantfix this issue, unless someone is going to take on the task of getting rid of the [filter syntax converter](https://github.com/gorhill/uBlock-for-firefox-legacy/blob/1f23453708721e10f8d57d57d96e21e4b41eddc1/src/js/assets.js#L265) and completely rewriting the parsing routine.

**Comment by hawkeye116477** [comment]
As I checked, seems that only first case which you mentioned works in `my filters` tab, but if it's in the filterlist, then case from my previous post is converted and works good.
Anyway, ok, fine, I'll try to adapt to new shorter names in filterlists :smile:

**Comment by JustOff** [comment]
`my filters` is a special case, see #228.

**Comment by AroKol78** [comment]
are changed so often that they cannot be constantly improved by hand, this is just an example - there is a lot more
https://github.com/MajkiIT/polish-ads-filter/commit/7334eec147caed2434f5bdf4d745fcc5f817c2e0

did not work
`abczdrowie.pl,autokult.pl,echirurgia.pl,film.wp.pl,fotoblogia.pl,gadzetomania.pl,gry.wp.pl,horoskop.wp.pl,kobieta.wp.pl,komorkomania.pl,medycyna24.pl,money.pl,parenting.pl,pogoda.wp.pl,tech.wp.pl,tv.wp.pl,twojeip.wp.pl,wiadomosci.wp.pl,wideo.wp.pl,www.wp.pl,sportowefakty.wp.pl,fitness.wp.pl,wawalove.wp.pl,gwiazdy.wp.pl,teleshow.wp.pl,www.wp.pl##+js(aost, WP.prebid, onLoad)`

it works
`abczdrowie.pl,autokult.pl,echirurgia.pl,film.wp.pl,fotoblogia.pl,gadzetomania.pl,gry.wp.pl,horoskop.wp.pl,kobieta.wp.pl,komorkomania.pl,medycyna24.pl,money.pl,parenting.pl,pogoda.wp.pl,tech.wp.pl,tv.wp.pl,twojeip.wp.pl,wiadomosci.wp.pl,wideo.wp.pl,www.wp.pl,sportowefakty.wp.pl,fitness.wp.pl,wawalove.wp.pl,gwiazdy.wp.pl,teleshow.wp.pl,www.wp.pl##+js(abort-on-property-read.js, WP.prebid, onLoad)`

**Comment by JustOff** [comment]
`aost` is simply not supported until #272 is ready.

https://github.com/gorhill/uBlock-for-firefox-legacy/blob/0608430e802d3e53d22c518d874afdc69e9deff7/src/js/assets.js#L293-L380

**Comment by AroKol78** [comment]
not only `aost`

it works `@@||smushcdn.com/*/blank.gif$image,domain=bithub.pl`
did not work `||smushcdn.com/*/blank.gif$image,domain=bithub.pl,redirect=1x1-transparent.gif`
look https://github.com/MajkiIT/polish-ads-filter/issues/17911#issuecomment-736092066

more and more it ceases to be compatible with anything

**Comment by JustOff** [comment]
If something specific does not work, open a separate issue according to the proposed template.

**Comment by AroKol78** [comment]
it's not about any specific page
the filters in the lists just stop working and become useless

**Comment by krystian3w** [comment]
Duplicate of #272
