### ISSUE TITLE
Too general blocking rules can't be exceptioned in some cases

### ISSUE THREAD

**Issue by THEtomaso** [gorhill/uBlock-for-firefox-legacy#237]
### Issue:
Initially reported in https://github.com/gorhill/uBlock-for-firefox-legacy/issues/229#issuecomment-647115856.

### How to reproduce (using uBO Legacy in Pale Moon):
1 - Add this blocking rule to your filters (found in 'Lunar Blocklist by Moonchild'):
`||pixel.`

2 - Open this page, and observe as all article images are blocked:
`https://www.thecut.com/2016/08/winona-ryder-c-v-r.html`

3 - Add one of the following whitelisting rules:
`@@||pixel.nymag.com/imgs/$doc,image`
or
`@@||pixel.nymag.com/imgs/$document,image`

4 - Reload the page, and observe as all article images are now shown.

5 - Now, right-click on one of the images, and select "View Image"..
The direct-linked image is now blocked!

6 - Add this whitelisting rule:
`@@||pixel.nymag.com/imgs/$all`

7 - Right-click on one of the images, and select "View Image" again..
The direct-linked image is now shown, while uBO's logger clearly states that it's allowed by the `$doc` variable.
So, why doesn't `$doc` or `$document` work?

### PS:
As noted by JustOff, in his post below the one that I linked to above, the issue is not related to the recently implemented `$all` and `$doc` syntax support.

**Comment by JustOff** [comment]
This should be resolved by backporting https://github.com/gorhill/uBlock/commit/41636c59fb4208544b4bb23a5ac6273399cab625.

Try [uBlock0_1.16.4.22b1.firefox-legacy.xpi.zip](https://github.com/gorhill/uBlock-for-firefox-legacy/files/4810043/uBlock0_1.16.4.22b1.firefox-legacy.xpi.zip).

**Comment by THEtomaso** [comment]
Yes, that fixed the problem!
But it actually rules out the need for `$document`, in this context, and allows the 301 convertion to take place without uBO interference.
I thought this was a Chromium weakness, but now it turns out that gorhill has made uBO more lenient on purpose!
Oh, well.. :)
Great work, as always, JustOff!
I can't even start to describe how much I appreciate all the work you've put into keeping uBO Legacy alive!!

**Comment by JustOff** [comment]
Resolved by https://github.com/gorhill/uBlock-for-firefox-legacy/commit/01325d109300e36c56196693df686b6a41f64350.
