### ISSUE TITLE
Element Picker and Element Zapper stopped working with Firefox 50

### ISSUE THREAD

**Issue by Mr6686** [gorhill/uBlock-for-firefox-legacy#244]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Element Picker and Element Zapper don't work anymore in new 1.16.4.22 legacy version.

### A specific URL where the issue occurs

https://github.com/gorhill/uBlock-for-firefox-legacy/issues

### Steps to Reproduce

1. Install Firefox 50.1.0
2. Install uBlock0_1.16.4.22.firefox-legacy.xpi
3. Select Element Picker

### Expected behavior:

Element picker is launched

### Actual behavior:

Nothing happen (no error in browser console)

### Your environment

* uBlock Origin version: 1.16.4.22
* Browser Name and version: Firefox 50.1.0
* Operating System and version: Windows 7 Pro SP1 64 bits

**Comment by JustOff** [comment]
Yep, apparently `for...of` loop construct with the `const` keyword [requires Firefox 52+](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of#Browser_compatibility), which was broken by https://github.com/gorhill/uBlock-for-firefox-legacy/commit/5306672b776fae1e487341c247a610fdf9d05c2a.

Please check [uBlock0_1.16.4.23b4.firefox-legacy.xpi.zip](https://github.com/gorhill/uBlock-for-firefox-legacy/files/4892656/uBlock0_1.16.4.23b4.firefox-legacy.xpi.zip) (rename to xpi).

**Comment by Mr6686** [comment]
Thank, this version fix all my problems.

**Comment by JustOff** [comment]
Don't rush closing the issue until the fix is released.

PS: Why FF50? There are tons of unpatched security issues.

**Comment by hawkeye116477** [comment]
I think that from a security perspective maybe minimum version should be bumped to 52 and `not waste time converting the upstream code to the old js syntax` :smile:

**Comment by JustOff** [comment]
Well, I still would like to try to maintain compatibility with at least Gecko 45+, primarily for [TenFourFox](https://github.com/classilla/tenfourfox) people who are following security updates so far. Gecko 45+ already has almost everything we need, including classes, and as far as I understand, only async/await will undoubtedly force the minimum supported version to 52. Let's see how long we can hold out.
