### ISSUE TITLE
Removed .xpi from SeaMonkey and ads are still being blocked

### ISSUE THREAD

**Issue by edwardp2** [gorhill/uBlock-for-firefox-legacy#256]
### Prerequisites

- [ X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Once extension/add-on was removed from SeaMonkey, ads continue to be blocked.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Removed extension from SeaMonkey.
2. Restarted SeaMonkey
3. Ads still being blocked

### Expected behavior:

Ads should no longer be blocked after removal of extension.

### Actual behavior:

Ads are still being blocked.

### Your environment

* uBlock Origin version: 1.16.4.24
* Browser Name and version: SeaMonkey 2.53.3
* Operating System and version: Linux x86_64 (Fedora 32)

It appears that when the add-on/extension was removed, it did not remove all remnants of the software. There were four 'ublock0' entries in the config file after removal of add-on. Those were removed by resetting them. Upon another relaunch of SeaMonkey, ads remain blocked.

**Comment by JustOff** [comment]
Please check if this happen when uBlock Origin is the only extension using a new, unmodified browser profile.

**Comment by edwardp2** [comment]
Testing on https://ads-blocker.com/testing/, the site instructs to see if there are ads on the left side of the page. Using a new profile, both with uBO installed and also after removal, there are no ads appearing on the left side of that page.

However, when testing on commercial web sites (Yahoo, MSN, etc.), the ads are appearing again, once uBO is removed.

**Comment by edwardp2** [comment]
Testing on https://ads-blocker.com/testing/, the site instructs to see if there are ads on the left side of the page. Using a new profile, both with uBO installed and also after removal, there are no ads appearing on the left side of that page.

However, when testing on commercial web sites (Yahoo, MSN, etc.), the ads are appearing again, once uBO is removed.

**Comment by JustOff** [comment]
> Testing on https://ads-blocker.com/testing/

Do not trust the results from this site, they are simply incorrect.
