### ISSUE TITLE
Toolbar button in Pale Moon on Windows looks inconsistent

### ISSUE THREAD

**Issue by JustOff** [gorhill/uBlock-for-firefox-legacy#257]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Toolbar button is too wide, has too much padding on both sides, and the icon is not symmetrically positioned.

Reported at https://forum.palemoon.org/viewtopic.php?t=25076&p=198154.

See also: https://github.com/uBlock-LLC/uBlock/issues/1315, https://github.com/uBlock-LLC/uBlock/pull/1321, https://github.com/uBlock-LLC/uBlock/issues/1449, https://github.com/gorhill/uBlock/issues/264.

### A specific URL where the issue occurs

`about:blank` and everywhere

### Steps to Reproduce

1. Install uBlock Origin
2. Make sure the button is placed on the main toolbar

### Expected behavior:

![palemoon_2020-08-29_12-57-15](https://user-images.githubusercontent.com/340855/91634355-7c9c4a00-e9f8-11ea-88ce-41b28d07299f.png)

### Actual behavior:

![palemoon_2020-08-29_12-53-21](https://user-images.githubusercontent.com/340855/91634363-845bee80-e9f8-11ea-83da-108fc35f95de.png)

### Your environment

* uBlock Origin version: 1.16.4.25
* Browser Name and version: Pale Moon 28.12.0
* Operating System and version: Windows 7 x64

**Comment by JustOff** [comment]
Here is a beta version to test: [uBlock0_1.16.4.26b1.firefox-legacy.xpi.zip](https://github.com/gorhill/uBlock-for-firefox-legacy/files/5145092/uBlock0_1.16.4.26b1.firefox-legacy.xpi.zip) (rename `xpi.zip` to `xpi` to install).

**Comment by epman100** [comment]
thanks.  the recent beta version worked great with Palemoon 28.13.0 on my PC.
when will 1.16.4.26 be final?

**Comment by epman100** [comment]
thanks.  the recent beta version worked great with Palemoon 28.13.0 on my PC.
when will 1.16.4.26 be final?

**Comment by JustOff** [comment]
This will happen as soon as it's ready. Until then, you can safely use this beta.
