### ISSUE TITLE
uBlock Origin reports negative number of used filters for some lists

### ISSUE THREAD

**Issue by reallyuniquename** [gorhill/uBlock-for-firefox-legacy#258]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBlock Origin reports negative number of used filters on `chrome://ublock0/content/dashboard.html`.

uBlock Origin ≤ 1.16.4.24 is not affected.

### A specific URL where the issue occurs

https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/admiral-domains.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt

### Steps to Reproduce

1. Import new filter list `https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/admiral-domains.txt`
2. Purge all caches
3. Update lists

### Expected behavior:

![image](https://user-images.githubusercontent.com/10516120/92153949-b1136a00-ee2d-11ea-9c4a-a457eef68729.png)

### Actual behavior:

![image](https://user-images.githubusercontent.com/10516120/92153887-993be600-ee2d-11ea-975b-6be54a66fb85.png)

### Your environment

* uBlock Origin version: 1.16.4.25
* Browser Name and version: Waterfox 2020.08.1
* Operating System and version: Windows 10

**Comment by JustOff** [comment]
Confirmed, the culprit is https://github.com/gorhill/uBlock-for-firefox-legacy/commit/29926eefe6851afcdfe2bb418c8cf31fff7b7185.

**Comment by JustOff** [comment]
It seems we need to backport https://github.com/gorhill/uBlock/commit/3a85158dbbaa9c855ae95218099c2ec69bb9e8a5.

**Comment by JustOff** [comment]
Please check [uBlock0_1.16.4.26b2.firefox-legacy.xpi.zip](https://github.com/gorhill/uBlock-for-firefox-legacy/files/5170976/uBlock0_1.16.4.26b2.firefox-legacy.xpi.zip) (rename `xpi.zip` to `xpi` to install).

**Comment by reallyuniquename** [comment]
>uBlock0_1.16.4.26b2.firefox-legacy.xpi

Fixed, thanks. 

Could you clarify, was it just cosmetic issue?

**Comment by JustOff** [comment]
> Could you clarify, was it just cosmetic issue?

Yes.
