### ISSUE TITLE
Opening uBO dashboard breaks browser refresh button (in Waterfox Classic)

### ISSUE THREAD

**Issue by Quisquose** [gorhill/uBlock-for-firefox-legacy#260]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When opening the uBO Dashboard, the browser's page Refresh button (at the end of the url / location bar) gets disabled for all _existing_ open tabs, and also for any _subsequent_ new tabs that are opened _after_ the uBO Dashboard. The refresh button icon changes from it's default circular arrow to an x, and it becomes unclickable.

Closing the uBO Dashboard tab does not restore the refresh button back to its working state (it remains unclickable in all tabs). However, the refresh button functionality is restored if the web browser is restarted.

This issue is not a recent development; it has been present in previous uBO legacy releases.

### A specific URL where the issue occurs

Occurs everywhere.

https://www.qwant.com/

### Steps to Reproduce

1. Open one or more browser tabs in Waterfox Classic
2. Open the uBO dashboard
3. Try to click on the url bar refresh button of any tab

_note:  self-contained portable version of Waterfox Classic (no installation required) is available here:_
(select 'Download Portable'   https://www.waterfox.net/download/#classic )
### Expected behavior:

The function of the refresh buttons should continue to work as normal (even if the uBO dashboard is open).

### Actual behavior:

None of the refresh buttons work (they all become unclickable).

### Your environment

* uBlock Origin version: 1.16.4.25
* Browser Name and version:  Waterfox Classic v2020.08.1
* Operating System and version: Windows 7

**Comment by JustOff** [comment]
This is a Waterfox Classic bug, there's something wrong with opening a new tab with the `chrome` protocol in the foreground.

It can be easily reproduced by running the following code in Scratchpad (Environment = Browser):

```js
var url = "chrome://browser/content/aboutRobots.xhtml";
var gBrowser = Services.wm.getMostRecentWindow('navigator:browser').gBrowser;
gBrowser.loadOneTab(url, {inBackground: false});
```

Attn to: @MrAlex94, @hawkeye116477.

**Comment by JustOff** [comment]
And here is the fix that needs to be backported to Waterfox Classic: https://bugzilla.mozilla.org/show_bug.cgi?id=1402493.
