### ISSUE TITLE
Confused about your legacy version

### ISSUE THREAD

**Issue by seamoonz** [gorhill/uBlock-for-firefox-legacy#261]
I have XP SP3 & FF ESR & Ublock 1.17.4 which version is new yours or mine? I see your release is quite new (August 2020) but your version number lower than latest ESR compatible Ublock.

**Comment by hawkeye116477** [comment]
For first, 1.17.4 is webextension. Version from this repo is legacy extension, it could be said that this is the fork, it was continued from last version, which had legacy extension code and some changes were ported from newer versions. So it can contain some changes which 1.17.4 doesn't contain, but it also may not have some things which 1.17.4 has (for example Per-site JavaScript master switch).

**Comment by seamoonz** [comment]
Thank you very much hawkeye116477. It's better to try and fail. But I'll use legacy version since it's still developing until I see any problems..

**Comment by seamoonz** [comment]
quickly I've found a bug. The video player of this site gives error with your version. Also disable all scripts option would be very useful like 1.17 has.
https://www.hdfilmcehennemi.net/1-adaletin-sembolu/

**Comment by JustOff** [comment]
> I've found a bug. The video player of this site gives error with your version.

Can't reproduce it with default settings. If this is caused by one of your filters, please report to their maintainers.

> Also disable all scripts option would be very useful like 1.17 has.

The work is in progress, see #263.
