### ISSUE TITLE
Update scriptlets from upstream (as of November 2020)

### ISSUE THREAD

**Issue by JustOff** [gorhill/uBlock-for-firefox-legacy#272]
Related sources:
- https://github.com/gorhill/uBlock/commits/master/assets/resources
- https://github.com/gorhill/uBlock/commits/master/src/web_accessible_resources

**Comment by JustOff** [comment]
See also: https://github.com/gorhill/uBlock-for-firefox-legacy/issues/228#issuecomment-712737982

**Comment by JustOff** [comment]
Here is the version to test: [uBlock0_1.16.4.27b4.firefox-legacy.xpi.zip](https://github.com/gorhill/uBlock-for-firefox-legacy/files/5688724/uBlock0_1.16.4.27b4.firefox-legacy.xpi.zip). Rename to xpi, install and purge all caches.
The scriptlets are upstream synchronized as of December 12th, remote update disabled.

I have installed this version in my main browser and going to release it by the end of the week if everything is ok.

**Comment by krystian3w** [comment]
https://github.com/gorhill/uBlock/commit/9d81b7c4d9fedf16ba74493481c1136fde7b1f3e

Maybe update from 2020 still have bug.
