### ISSUE TITLE
problem "Fullwidth Plus Sign"

### ISSUE THREAD

**Issue by AroKol78** [gorhill/uBlock-for-firefox-legacy#276]
### Your environment

* uBlock Origin version: uBlock firefox legacy 1.16.4.26
* Browser Name and version: Firefox 52.9 esr
* Operating System and version: win xp

apparently there is support Firefox 52.9 esr
https://github.com/gorhill/uBlock-for-firefox-legacy/blob/a6b92135d66049d24cc23d3e584a432a6e08fb19/platform/firefox/install.rdf#L24
system use region/language polish = ok
when I switch my browser to english there is "Fullwidth Plus Sign" which is a problem
![ublockFix0](https://user-images.githubusercontent.com/70756447/98251891-9d919600-1f79-11eb-8159-f25c37d474b1.PNG)

https://github.com/gorhill/uBlock-for-firefox-legacy/pull/274#issuecomment-722702915 the same is possible with english

**Comment by JustOff** [comment]
You've already been told that this is a unicode display issue in Windows XP, and not a uBO issue.

PS: The solution can be googled in two minutes: [Arial Unicode MS font](https://www.google.com/search?q=arial+unicode+ms+download).

**Comment by AroKol78** [comment]
You are great  @JustOff 🥇
It helped 👍
