### ISSUE TITLE
All has-text cosmetic filters logged as invalid in 1.16.4.24+

### ISSUE THREAD

**Issue by 0strodamus** [gorhill/uBlock-for-firefox-legacy#278]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

All has-text cosmetic filters are logged as invalid. The logger will output "Cosmetic filtering – invalid filter:" messages for all cosmetic filters containing "has-text". I back tested and found that the issue began with version 1.16.4.24 and continues to the latest version 1.16.4.26. 1.16.4.23 works fine and does not generate the logger errors. At first blush, it appears from the logger messages that the URL and hashtags are being removed from the filter, but in messing around with some purposely invalid filters in 1.16.4.23, I think this may be normal extension behavior.

### A specific URL where the issue occurs

I'll give you 2, but this issue occurs with any has-text cosmetic filter. You don't need to visit any site to generate the errors. Just create some filters and watch the logger.

filter: yelp.com##li:has-text(Ad)
logger: Cosmetic filtering – invalid filter: li:has-text(Ad)

filter: digg.com##.digg-story:has-text(SPONSORED)
logger: Cosmetic filtering – invalid filter: .digg-story:has-text(SPONSORED)

### Steps to Reproduce

1. Create a "has-text" cosmetic filter in "My Filters".
2. Open a logger tab and select "All" or "Behind the Scene" from the drop-down list.
2. Edit something in "My Filters".
3. Switch to the logger tab and see the "Cosmetic filtering – invalid filter:" errors for every "has-text" filter in the ruleset.

### Expected behavior:

The behavior of 1.16.4.23, where "has-text" filters do not generate errors in the log.

### Actual behavior:

All "has-text" filters generate errors in the log.

### Your environment

* uBlock Origin version: 1.16.4.24, 1.16.4.25, or 1.16.4.26 (tested all)
* Browser Name and version: Palemoon 28.15.0 or Palemoon 28.16.0 (tested with both)
* Operating System and version: Arch Linux x64

Thanks for keeping uBlock Origin updated for Palemoon. I haven't been able to so far, but if I can figure out a fix for this, I will provide a patch.

**Comment by JustOff** [comment]
Please check [uBlock0_1.16.4.27b2.firefox-legacy.xpi.zip](https://github.com/gorhill/uBlock-for-firefox-legacy/files/5611957/uBlock0_1.16.4.27b2.firefox-legacy.xpi.zip) (rename to xpi).

**Comment by 0strodamus** [comment]
uBlock0_1.16.4.27b2.firefox-legacy.xpi.zip is working. Thanks!
