### ISSUE TITLE
little fix cosmetic ui

### ISSUE THREAD

**Issue by AroKol78** [gorhill/uBlock-for-firefox-legacy#282]
applies to uBlock0_1.16.4.27b2.firefox-legacy beta test from https://github.com/gorhill/uBlock-for-firefox-legacy/issues/278#issuecomment-735367593
this is just my suggestion - active places choice ( applies to all :ballot_box_with_check::black_square_button: in Settings/Filter lists)
![fixubol01](https://user-images.githubusercontent.com/70756447/101246520-2ab04200-3714-11eb-8cee-f597be1b41d2.PNG)

:blue_square: is ok
:green_square: should be
:red_square: now is

**Comment by JustOff** [comment]
Sorry, but design changes that are not consistent with the upstream are not considered.

**Comment by AroKol78** [comment]
> that are not consistent with the upstream are not considered.

applies to a future version - the changes have already been introduced / accepted in "Pull requests"
that's what the beta is for to check, refine

**Comment by JustOff** [comment]
Then it is better to link to specific changes in the upstream when they are released. But in any case, a request for cosmetic changes has a minimum priority, unless someone offers a ready-made solution as a pull request.
