### ISSUE TITLE
Reuse duplicate strings stored in tries

### ISSUE THREAD

**Issue by SampeiNihira** [gorhill/uBlock-for-firefox-legacy#283]
References:
https://github.com/gorhill/uBlock/commit/c77f697b4b7b1060a5e3217116c2920d81bfb77b

Note:
Obvious problem in "Online Malicious URL Blocklist" that has gone to twice as many rules in the last few days than before.

**Comment by AroKol78** [comment]
e.g. one `$all` = x5
not only "Online Malicious URL Blocklist"  - e.g. "KAD - Przekręty"

**Comment by nicolaasjan** [comment]
Two files `./src` are changed: `hntrie.js` and `strie.js`.
But in uBlock-for-firefox-legacy `strie.js` is not present...

**Comment by gwarser** [comment]
This commit is about memory usage optimization. Upstream uBO counted `$all` as 5 filters from the beginning, so I don't understand why: 

> Obvious problem in "Online Malicious URL Blocklist" that has gone to twice as many rules in the last few days than before.

Is a "obvious problem".

Some other types of filters are also counted multiple times.

**Comment by AroKol78** [comment]
> This commit is about memory usage optimization.

👍
yes please ( ubo legacy - sometimes hardware legacy)

**Comment by nicolaasjan** [comment]
@gwarser,
That's where he started noticing it, I guess... ;)
There are a lot of `$all` instances in that list.

**Comment by krystian3w** [comment]
PS. malware/scam start use `Base64` for images and linline script/style:

```js
<script>
! blah - malware injected js
</script>
```
```css
<style>
/* blah - page looks good, no likes from 1995 without stylize */
</style>
```

so network filters may no longer protect if page save private data pure by html5 forms based on `post="..." `/ `action="..."`.

**Comment by AroKol78** [comment]
> so network filters may no longer protect

**krystian3w** - "Online Malicious URL Blocklist" and "KAD - Przekręty" is this a good choice?

**Comment by JustOff** [comment]
As far as I can tell, this optimization cannot be applied to the uBlock-for-firefox-legacy codebase in its current state.
