### ISSUE TITLE
Issues with svg icons in redesigned dashboard on Gecko 45-51

### ISSUE THREAD

**Issue by JustOff** [gorhill/uBlock-for-firefox-legacy#287]
There are several issues with svg icons in [redesigned dashboard](https://github.com/gorhill/uBlock-for-firefox-legacy/pull/274) on Gecko 45-51:

1. The `for ( const` loop need to be replaced with `for ( let`

https://github.com/gorhill/uBlock-for-firefox-legacy/blob/437c899adbbdbf4515f3e587f1674d888e5159d7/src/js/fa-icons.js#L28

2. The old Gecko versions do not support [svg  use](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use) `href` attribute, so svg icons are not visible at all

I tried to use [`xlink:href`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href) instead of `href`, but that only worked for checkboxes statically defined in `settings.html` and `3p-filters.html`, but not for `fa-icons.js`-generated icons.

I believe we should still try to fix this by providing some workaround, primarily for [TenFourFox](https://github.com/classilla/tenfourfox).

@hawkeye116477, could you please take a look at this?

**Comment by hawkeye116477** [comment]
Maybe https://github.com/jonathantneal/svg4everybody would help.

**Comment by JustOff** [comment]
Well, it seems I managed to beat it with this change in `fa-icons.js`:

```diff
-        use.setAttribute('href', href);
+        use.setAttributeNS('http://www.w3.org/1999/xlink', 'href', href);
```

**Comment by JustOff** [comment]
Here is beta version to test: [uBlock0_1.16.4.28b2.firefox-legacy.xpi.zip](https://github.com/gorhill/uBlock-for-firefox-legacy/files/5730210/uBlock0_1.16.4.28b2.firefox-legacy.xpi.zip) (rename zip to xpi to install).
