### ISSUE TITLE
Fix the handling of pseudoclass-based generic cosmetic filters

### ISSUE THREAD

**Issue by THEtomaso** [gorhill/uBlock-for-firefox-legacy#290]
This used to work just fine, but apparently uBO Legacy has now been affected by the same regression bug as the main branch was, back in 2019:
https://github.com/uBlockOrigin/uBlock-issues/issues/464/

CSS selector-based cosmetic filters test:
https://gorhill.github.io/uBlock/tests/css-selector-based-cosmetic-filters.html

Culprit:
https://github.com/gorhill/uBlock-for-firefox-legacy/pull/279/

Fix (main branch):
https://github.com/gorhill/uBlock/commit/f10b1003793a54d5d04c819e94cad02c78e10a82/

**Comment by JustOff** [comment]
@THEtomaso, please check out [uBlock0_1.16.4.28b4.firefox-legacy.xpi.zip](https://github.com/gorhill/uBlock-for-firefox-legacy/files/5838408/uBlock0_1.16.4.28b4.firefox-legacy.xpi.zip) built with #291 applied.

**Comment by THEtomaso** [comment]
I can confirm that `:before` / `:after` works in generic rules again! 👍

**Comment by JustOff** [comment]
Thanks for confirming!
