### ISSUE TITLE
Easylist Cookie List - URL needs to be updated!

### ISSUE THREAD

**Issue by THEtomaso** [gorhill/uBlock-for-firefox-legacy#293]
**Easylist Cookie List** seems to have been removed from this URL now:
`https://easylist-downloads.adblockplus.org/easylist-cookie.txt`

Therefore, the filter's contentURL needs to be updated in uBO Legacy, to the one currently used by uBO's main branch, which is this one:
`https://secure.fanboy.co.nz/fanboy-cookiemonster.txt`

**Comment by JustOff** [comment]
Thanks for reporting!
