### ISSUE TITLE
Just a quick question

### ISSUE THREAD

**Issue by 737simpilot** [gorhill/uBlock-for-firefox-legacy#295]
With you moving to Github for extension updates, I did get an alert from Remove the overlay. But does this extension use Github for updates or will I have to uninstall it too and reinstall from here? I'm thinking no. 

Pale Moon has really pissed me off over the years. Sorry you had to go through this.

**Comment by JustOff** [comment]
Sorry, but obviously you wrote in the wrong place. The move of my extensions has nothing to do with uBlock Origin for Firefox legacy-based browsers, where I am just a contributor and release coordinator. Nothing has changed here.
