### ISSUE TITLE
uBlock supports DNS leak even with DOH, another DNS provider and proxy

### ISSUE THREAD

**Issue by snoitallicso** [gorhill/uBlock-for-firefox-legacy#297]
### Steps to Reproduce

(optional) 1. Change your proxy settings directly or install proxy extension and setup your another location
2. Change settings in Preferences > Network Settings > **Enable DNS over HTTPS** and **Proxy DNS when using SOCKS v5**
3. Setup CloudFlare or NextDNS as **Use provider** (DNS)
4. Open https://browserleaks.com/ip
5. Look up for **Your DNS Servers** row

### Expected behavior:

DNS servers expects to be external, not your ISP's

### Actual behavior:

In DNS servers row my ISP IP addresses + external. 

### How I fixed it

I removed (disable) uBlock Origin and now all works fine. Settings like

- Disable pre-fetching (to prevent any connection for blocked network requests) 
- Disable hyperlink auditing 
- Prevent WebRTC from leaking local IP addresses 
- Block CSP reports

not fix it even been checked

### My environment

* uBlock Origin version: 1.33.2
* Browser Name and version: Firefox 86.0
* Operating System and version: Debian Linux 10

**Comment by JustOff** [comment]
> uBlock Origin version: 1.33.2
> Browser Name and version: Firefox 86.0

Please fill your report in [uBlock-issues](https://github.com/uBlockOrigin/uBlock-issues).

**Comment by gwarser** [comment]
@snoitallicso browser issue, you can disable CNAME uncloaking https://github.com/uBlockOrigin/uBlock-issues/issues/911
