### ISSUE TITLE
privacy and remote fonts

### ISSUE THREAD

**Issue by make-it-really-easy** [gorhill/uBlock-for-firefox-legacy#299]
'privacy and remote fonts' 

To the administrator:

I can not write at the closed thread.

I have not also known that replying to email actually make post at the forum.

That issue is not clarified.

That option is for privacy.

Blocking remote fonts is good for privacy - it prevents the remote server to know when your website is loaded (remote server know which website loads the fonts  ).  But this option spoils webpages that really care about privacy and do not load fonts from remote servers but keeps them locally at the same place - where it keeps pictures, html, css, js documents and so on.

**Comment by make-it-really-easy** [comment]
Why You have closed this. I am new here. Please help me with that issue.

**Comment by JustOff** [comment]
[Do not abuse the issue tracker and the time of volunteers](https://github.com/uBlockOrigin/uBlock-issues/issues/1524).
