### ISSUE TITLE
search bug ?

### ISSUE THREAD

**Issue by AroKol78** [gorhill/uBlock-for-firefox-legacy#301]
wrong search/results for `///` and `////`
for example for el
`chrome://ublock0/content/asset-viewer.html?url=easylist`

**Comment by gwarser** [comment]
What you think is wrong?

Enclosing search in `/.../` makes it regular expression.

**Comment by AroKol78** [comment]
I wanted to search for 3x / 4x characters `/` (i was looking for typos)
3x = select double and single characters
4x = select double characters
should not select anything
