### ISSUE TITLE
ui bug?

### ISSUE THREAD

**Issue by AroKol78** [gorhill/uBlock-for-firefox-legacy#303]
[uibug000.png](https://user-images.githubusercontent.com/70756447/115111168-3d1e7000-9f7f-11eb-8534-e3d89a461167.PNG) - `https://www.facebook.com/ISS`
possible association with a similar error https://github.com/gorhill/uBlock-for-firefox-legacy/issues/292
UXP - master - last

**Comment by JustOff** [comment]
https://github.com/gorhill/uBlock-for-firefox-legacy/issues/292#issuecomment-774678975

**Comment by AroKol78** [comment]
![uibug001](https://user-images.githubusercontent.com/70756447/117141883-5a40a480-adaf-11eb-81d0-7c6440388984.PNG)
`https://www.flickr.com/photos/nasahqphoto/`

**Comment by gwarser** [comment]
These numbers are limited to 99 in upstream.
