### ISSUE TITLE
little update

### ISSUE THREAD

**Issue by AroKol78** [gorhill/uBlock-for-firefox-legacy#304]
- Ensure getter/setter are called with proper context
from https://github.com/gorhill/uBlock/commit/e4b8f2ef2d0db2ef210e27b35849b0033809168d
only two lines (1694 &1700) to replace in https://github.com/gorhill/uBlock-for-firefox-legacy/blob/master/assets/resources/resources.txt#L1694-L1700
- Use zero-based index for id
from https://github.com/gorhill/uBlock/commit/cdf6088dfa2570ecb95d833402b44ec1d46f195d
only one line to replace in https://github.com/gorhill/uBlock-for-firefox-legacy/blob/master/assets/resources/resources.txt#L599
- Add missing getResponseInformation() method to neutered JS API
from https://github.com/gorhill/uBlock/commit/d307bbd1340996bb27c0019f2a278b78ace61296
put only one line before https://github.com/gorhill/uBlock-for-firefox-legacy/blob/master/assets/resources/resources.txt#L517

**Comment by AroKol78** [comment]
Add support for "remove all properties" in json-prune scriptlet  - from https://github.com/gorhill/uBlock/commit/d338e4c4b6caf339873a60c9d48fde58e9a495ce
https://github.com/gorhill/uBlock-for-firefox-legacy/blob/master/assets/resources/resources.txt#L1549

**Comment by JustOff** [comment]
Resolved by [1.16.4.29](https://github.com/gorhill/uBlock-for-firefox-legacy/releases/tag/firefox-legacy-1.16.4.29).
