### ISSUE TITLE
Power button completely wrong, open the logger button missing (white on white background) at XP

### ISSUE THREAD

**Issue by spyrosmas** [gorhill/uBlock-for-firefox-legacy#305]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by spyrosmas** [comment]
Github preview and image drag drop not working on mypal even with all extensions disabled.
JustOff 's github-wc-polyfill-1.1.8.xpi says not compatible with mypal on xp
![power button](http://www.neapolirooms.gr/powerbuttonxp.png)

**Comment by AroKol78** [comment]
You have some strange version of ubo (compare the icons at the bottom)
I just checked and I have ok and image drag and drop also works
![jestok](https://user-images.githubusercontent.com/70756447/119352772-64650d00-bca2-11eb-89a3-2c95c877d041.PNG)

**Comment by JustOff** [comment]
Please update the issue with all the data requested in the [template](https://github.com/gorhill/uBlock-for-firefox-legacy/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by spyrosmas** [comment]
@AroKol78 Nothing strange here. I found the problem after I completely lost my profile through several re-installations of mypal versions.  

"Allow pages to choose their own fonts, instead of my selections above" must be checked for power button to draw correctly, but this has side effect that some sites like outlook.live.com and many others display their own version of fonts; eg. italics in sign up form or draw whole pages with Times New Roman which is crap left from ancient calligraphy times.

So my conclusion is that the ubo drop-down menu is some kind of web page :(

@JustOff Running Mypal 29.2.0 on XP github buttons like add bold text, add italic text, insert code, etc and preview does NOTHING. The Attach files on github show the system selection dialog for file upload but does not upload the image and does not work. Finally I manage to install github-wc-polyfill-1.1.8.xpi on my new mypal profile.

**Comment by spyrosmas** [comment]
With github-wc-polyfill installed on mypal 29.2.0 on XP the github buttons and upload files are OK.
