### ISSUE TITLE
Does it work with the latest palemoon 29.2.0?

### ISSUE THREAD

**Issue by rubyFeedback** [gorhill/uBlock-for-firefox-legacy#306]
I remember the legacy version worked fine for palemoon 29.1.0 or so.

Now I can not install it; palemoon says it can not modify the file. Quite confused
so I wonder if this is a problem only I have or others may as well.

**Comment by JustOff** [comment]
Please update the issue with all the data requested in the [template](https://github.com/gorhill/uBlock-for-firefox-legacy/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by JustOff** [comment]
The required information is not provided by the reporter.
