### ISSUE TITLE
Power button draws wrong when "Allow pages to choose their own fonts, instead of my selections above" setting is off.

### ISSUE THREAD

**Issue by spyrosmas** [gorhill/uBlock-for-firefox-legacy#307]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Power button draws wrong when "Allow pages to choose their own fonts, instead of my selections above" setting is off.

### A specific URL where the issue occurs
about:blank (= everywhere)

### Steps to Reproduce

1. Go to Tools->Preferences->Content->Advanced
2. Uncheck the "Allow pages to choose their own fonts, instead of my selections above" setting
3. Click on ubo shield alike icon on the navigation toolbar.

### Expected behavior:

The power button and any other clickable options must be draw correctly at all times

### Actual behavior:

Probably the font/svg/image that is responsible to have the power button icon is getting changed by the default font which does not have the power button icon on the same unicode/font position as the responsible font.

### Your environment

* uBlock Origin version: 1.16.4.28
* Mypal 29.2.0 (32-bit)
* Windows XP SP3 and unofficial SP4 by harkaz
![ubo power button](https://user-images.githubusercontent.com/18444690/119704342-634fef00-be0c-11eb-83a0-356d69ce32ef.png)

**Comment by JustOff** [comment]
This is by design.

**Comment by spyrosmas** [comment]
So, this is a **bug by design**!
Then the design is wrong and must be stay as a bug. In that case I can suggest the power button icon should be loaded as a standard icon or image and not as a Unicode symbol. Am I wrong? As I know, add-ons can load icons and or image files.

Also, check side by side comparison of "Allow pages to choose their own fonts, instead of my selections above" to see for your own. Must be seen at full screen. 

![ubo site fonts off](https://user-images.githubusercontent.com/18444690/119708003-a9a74d00-be10-11eb-82fd-02de8c017af5.png)
![ubo site fonts on (aka default behaviour with power button show correctrly)](https://user-images.githubusercontent.com/18444690/119708005-aa3fe380-be10-11eb-8279-64c78d4de818.png)
