### ISSUE TITLE
Ubo icon not centered in CTR addon-bar ((

### ISSUE THREAD

**Issue by xlovinglyx** [gorhill/uBlock-for-firefox-legacy#308]
"Waterfox Legacy" V2021.06 + ublock origin v1.16.4.28

Hi,

With Classic Theme Restorer extention to obtain a bottom addon-bar,
there's a strange gap between The fish icon "Unplug extention" &
when pages are blocked the numbers appear behind "S3 translator icon (last one).

![x](https://user-images.githubusercontent.com/53103638/121764839-32c7bf00-cb47-11eb-9cdd-ccc2303903b7.png)

Could you provide me a css to slide ubo a little bit to the left, && i'll tweak the value
to center it.

Thanks

**Comment by JustOff** [comment]
Please direct such questions to the [Waterfox community](https://www.reddit.com/r/waterfox/).

**Comment by xlovinglyx** [comment]
they don't know & aren't very cooperative. & gorhill will certainly have more knowledge
about css with ub icon
