### ISSUE TITLE
Add support for $queryprune parameter

### ISSUE THREAD

**Issue by THEtomaso** [gorhill/uBlock-for-firefox-legacy#309]
_duplicate_ ( https://github.com/gorhill/uBlock-for-firefox-legacy/issues/289 )

**Comment by AroKol78** [comment]
uBlock-for-firefox-legacy does not support `$removeparam`

**Comment by THEtomaso** [comment]
> uBlock-for-firefox-legacy does not support `$removeparam`

Dang, I thought this was added in v1.16.4.24, but indeed, that was a different thing all together. :(
