### ISSUE TITLE
Integrate strict-blocking security fix from uBlockOrigin repo

### ISSUE THREAD

**Issue by vtriolet** [gorhill/uBlock-for-firefox-legacy#310]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Can the security fix for https://github.com/uBlockOrigin/uBlock-issues/issues/1649 be applied to this repo, as well?

I confirmed that the DoS issue also affects the legacy extension and Pale Moon.

Thank you.

### Your environment

* uBlock Origin version: 1.16.4.29
* Browser Name and version: Pale Moon 29.2.1
* Operating System and version: Arch Linux

**Comment by JustOff** [comment]
Thank you. As soon as I come back from vacation, I will release the necessary update. Fortunately, the problem itself does not look so critical to require immediate intervention.

**Comment by JustOff** [comment]
Resolved in [firefox-legacy-1.16.4.30](https://github.com/gorhill/uBlock-for-firefox-legacy/releases/tag/firefox-legacy-1.16.4.30).

**Comment by vtriolet** [comment]
Thanks for the release.
