### ISSUE TITLE
Blocking remote fonts breaks gitlab

### ISSUE THREAD

**Issue by l29ah** [gorhill/uBlock-for-firefox-legacy#311]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When remote fonts are forbidden in ublock, then the tabs on that page don't show any content.

### A specific URL where the issue occurs

https://gitlab.com/pkill-9

### Steps to Reproduce

Open the link and poke around the tabs.

### Expected behavior:

Content.

### Actual behavior:

No content.

### Your environment

* uBlock Origin version: v1.16.4.29
* Browser Name and version: palemoon 29.2.1
* Operating System and version: Gentoo GNU/Linux

**Comment by JustOff** [comment]
This is not a uBlock Origin issue, see https://github.com/JustOff/github-wc-polyfill/issues/26.
