### ISSUE TITLE
Disappearing log entries

### ISSUE THREAD

**Issue by THEtomaso** [gorhill/uBlock-for-firefox-legacy#312]
I've noticed a new issue in uBO Legacy (v1.16.4.30)..
Sometimes, when clicking on certain red entries in the logger, the page that I'm investigating suddenly refreshes, and the entry disappears (along with some other ones).

**Comment by JustOff** [comment]
Sorry, but the issues that cannot be reproduced cannot be resolved.

**Comment by THEtomaso** [comment]
That's OK.
So far, I've only run into this issue 3 times.
If I encounter it again, and find a way to properly reproduce it, I'll post the info here.
