### ISSUE TITLE
Wrong minimum version check for SeaMonkey

### ISSUE THREAD

**Issue by dryeo** [gorhill/uBlock-for-firefox-legacy#313]
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Attempting to install the latest results in a message about my browser not being supported

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]
https://github.com/gorhill/uBlock-for-firefox-legacy/releases/tag/firefox-legacy-1.16.4.30

### Steps to Reproduce

1. Attempt to install by clicking the xpi or downloading and drag'n'dropping and get message my version of SeaMonkey is not supported
2. Edit install.rdf so em:minVersion for SeaMonkey is 2.42
3. Successfully install a working ublock_origin

### Expected behavior:

A simple install to work.

### Actual behavior:

Failure

### Your environment

* uBlock Origin version: Now, firefox-legacy-1.16.4.30
* Browser Name and version: Mozilla/5.0 (OS/2; Warp 4.5; rv:45.0) Gecko/20100101 Firefox/45.0 SeaMonkey/2.42.9esr
* Operating System and version: ArcaOS 5.0.6.10 EN, Built 2021-07-04 12:10:42 (OS/2 4.52 based)

PS, sorry about the formatting, old browser doesn't seem to support the JS and it did say not to delete the template

**Comment by dryeo** [comment]
```
From 2d6a01e2d0386c57bbeae4652d9683abf15e47c6 Mon Sep 17 00:00:00 2001
From: Dave Yeo <dave.r.yeo@gmail.com>
Date: Thu, 29 Jul 2021 20:19:18 -0700
Subject: [PATCH] Align SeaMonkey minimum version with Firefox

While no official release, there are versions of SeaMonkey 2.42 being used

Signed-off-by: Dave Yeo <dave.r.yeo@gmail.com>
---
 platform/firefox/install.rdf | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/platform/firefox/install.rdf b/platform/firefox/install.rdf
index add21688..5432f38f 100644
--- a/platform/firefox/install.rdf
+++ b/platform/firefox/install.rdf
@@ -39,7 +39,7 @@
         <em:targetApplication>
             <Description>
                 <em:id>{{92650c4d-4b8e-4d2a-b7eb-24ecf4f6b63a}}</em:id>
-                <em:minVersion>2.46</em:minVersion>
+                <em:minVersion>2.42</em:minVersion>
                 <em:maxVersion>2.*</em:maxVersion>
             </Description>
         </em:targetApplication>
-- 
2.11.0
```

**Comment by JustOff** [comment]
Sorry, but support for this ancient and not official version will not be considered.
