### ISSUE TITLE
New issue with the new legacy dumping palemoon releases

### ISSUE THREAD

**Issue by xlovinglyx** [gorhill/uBlock-for-firefox-legacy#314]
You've posted an alpha version of moon tester tool for a previous issue with it.
And i don't know when the problem started but i believe, it started from ubo for fx
legacy 1.16.4.30, i returned to .29 but even addons are slow to opennow. maybe
leftovers remains in the prefs file.  In fact 1.16.4.30 is effective now on getting rid of
crappy adds on xhamster but it's unusable as it slows my navigation like hell. you wait
ages between pages for actions to take place, "clicks" etc, its absolutely not usable with pm
29.3.0, what would you suggest ?

**Comment by JustOff** [comment]
Sorry, but you have chosen the wrong place for this question. You'd better ask it [here](https://www.reddit.com/r/palemoon/).
