### ISSUE TITLE
Hi, so to resume

### ISSUE THREAD

**Issue by xlovinglyx** [gorhill/uBlock-for-firefox-legacy#315]
You could have waited my reply before closing, so my reply is:

1) you help me with moon testing tool to support all other addons,
and now you reject theissue i'm facing with palemoon using your
tweaked version of ublock & believe reddit will respond about your
own ublock coding practices better than you ? strange.

2) do i have to use moon tester for your .30 version of ublock that slowspm to hell,
from your .28 or get rid of ublock legacy forever & try another option from pm' s addons ?
which means you sadly won't correct the bugs encountered in pm with ur latest version of ublock
if ur dropping support for pm 

3) i'm not retarded, no need to send me to reddit who won't be tweaking ur version for pm.
if ur dropping pm support for ur legacy version of ublock just mention it & block me then,
but be honest, even if it puts me down & forces me to look elsewhere.

in ur legacy version, it'd be a great loss, cuz .30 blocks crazy addons
like from xhamster properly.

You've posted an alpha version of moon tester tool for a previous issue with it.
And i don't know when the problem started but i believe, it started from ubo for fx
legacy 1.16.4.30, i returned to .28 but even addons are slow to opennow. maybe
leftovers remains in the prefs file. In fact 1.16.4.30 is effective now on getting rid of
crappy adds on xhamster but it's unusable as it slows my navigation like hell. you wait
ages between pages for actions to take place, "clicks" etc, its absolutely not usable with pm
29.3.0, what would you suggest ?

@JustOff
Collaborator
JustOff commented Aug 3, 2021

Sorry, but you have chosen the wrong place for this question. You'd better ask it here.

**Comment by JustOff** [comment]
Please respect the [answer](https://github.com/gorhill/uBlock-for-firefox-legacy/issues/314) you have been given already and do not spam with new issues.

**Comment by xlovinglyx** [comment]
You help someone with a tool & then abandon him the next week & expect respect.
i then respect ur attitude, but i'm starting to understand tobin a lot better now.

adieu.
