### ISSUE TITLE
Enable the syntax converter for more filters

### ISSUE THREAD

**Issue by THEtomaso** [gorhill/uBlock-for-firefox-legacy#324]
Reference:
https://github.com/easylist/easylist/issues/10035#issuecomment-994794684

**Comment by JustOff** [comment]
> `danskebank.*##+js(remove-class, cookie-consent-banner-open, html)`

Where does this rule come from? I do not see it in [EasyList Cookie](https://secure.fanboy.co.nz/fanboy-cookiemonster.txt).

**Comment by THEtomaso** [comment]
https://github.com/easylist/easylist/blob/c2022168ac21d7e5f7b9118cb42651e3a6e134c9/easylist_cookie/easylist_cookie_specific_uBO.txt#L138

**Comment by JustOff** [comment]
I don't see this list mentioned anywhere in [assets.json](https://github.com/gorhill/uBlock-for-firefox-legacy/blob/master/assets/assets.json).

**Comment by AroKol78** [comment]
https://github.com/gorhill/uBlock-for-firefox-legacy/blob/master/assets/assets.json#L202

**Comment by JustOff** [comment]
No, that corresponds to https://secure.fanboy.co.nz/fanboy-cookiemonster.txt, which is not easylist_cookie_specific_uBO.txt.

**Comment by AroKol78** [comment]
`chrome://ublock0/content/asset-viewer.html?url=fanboy-cookiemonster`

![haha1](https://user-images.githubusercontent.com/70756447/146220707-ca6c6978-a523-44f6-9e5a-7b2f5d749f2a.PNG)

**Comment by THEtomaso** [comment]
> No, that corresponds to https://secure.fanboy.co.nz/fanboy-cookiemonster.txt, which is not easylist_cookie_specific_uBO.txt.

It's loaded through `!#include easylist_cookie_specific_uBO.txt`

**Comment by JustOff** [comment]
Ahh, my bad, now I see. Do we need to enable syntax converter for any other additional lists except EasyList Cookie and Fanboy's Annoyance?

**Comment by THEtomaso** [comment]
https://github.com/easylist/easylist/commit/1ff6f0c7ebbdd1a8f492e9eb9fa2e3895bdac798

**Comment by AroKol78** [comment]
"adguard-spyware" --> AdGuard Tracking Protection

**Comment by THEtomaso** [comment]
**AdGuard Social Media filter** currently only has one rule, which needs to be converted too.

**Comment by THEtomaso** [comment]
`"noConvert":` really aren't used for that many filters.
At this point, removing it all together might be the best solution.

**Comment by THEtomaso** [comment]
Guess we're OK, if you disregard that one rule in AdGuard Social Media filter :)

**Comment by AroKol78** [comment]
how to force updates `assets.json`
`chrome://ublock0/content/asset-viewer.html?url=fanboy-cookiemonster`
I still have `+js(rc,` - not converted

**Comment by JustOff** [comment]
`Purge all caches` + `Update now` **twice**.

**Comment by AroKol78** [comment]
i tried several (> 10) times before and now - it doesn't work on `assets.json`

**Comment by THEtomaso** [comment]
> it doesn't work

Confirmed

**Comment by AroKol78** [comment]
in "logger" show `https://raw.githubusercontent.com/gorhill/uBlock-for-firefox-legacy/master/assets/assets.json`

that is, maybe it doesn't convert lists as they are disabled by default

**Comment by JustOff** [comment]
> that is, maybe it doesn't convert lists as they are disabled by default

Of course you should enable them, otherwise they are not downloaded and accordingly are not converted.

**Comment by AroKol78** [comment]
we don't understand each other
I turn on the list "EasyList Cookie", clear the cache, update, close the browser with the list "EasyList Cookie" attached
then next i start the browser and I still have `+js(rc,`

**Comment by THEtomaso** [comment]
> I turn on the list "EasyList Cookie", Purge all caches + Update now , close the browser with the list "EasyList Cookie" attached then next i start the browser and I still have `+js(rc,`

Same here.

**Comment by JustOff** [comment]
It should be fixed now.
