### ISSUE TITLE
Restore green "Allow" field for dynamic filters

### ISSUE THREAD

**Issue by VLLib** [gorhill/uBlock-for-firefox-legacy#325]
Hi, I apologize for posting this here, but I'm not aware of any other place to post it. In the old version of uBO, there were 3 dynamic filter options, green (allow), gray (no-op), and red (disallow/block). Now in Firefox, I just installed uBO, and I see only the gray and red filter options. Is there a way to restore the green option? Where might I look in the documentation? I ask, because for some reason, the no-op option doesn't always accomplish what is intended.

Thank you very much. 

### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by JustOff** [comment]
> Where might I look in the documentation?

https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide#allow-rules

> Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)

**^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^**
