### ISSUE TITLE
uBlock icon is missing/not working in Pale Moon

### ISSUE THREAD

**Issue by dustylancer** [gorhill/uBlock-for-firefox-legacy#327]
### Prerequisites

- [+ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [+] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [+] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [+] uBlock Origin is the only extension
    - [+] uBlock Origin with default lists/settings
    - [+] using a new, unmodified browser profile
- [+] I am running the latest version of uBlock Origin
- [+] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The uBlock icon has disappeared from the toolbar.

### Expected behavior:

After installing the extension the uBlock icon should appear in the top right corner of the browser in order to access the extension.

### Actual behavior:

Upon installation there is confirmation message that the extension was successfully installed. It shows in the addons menu as well. However, the icon for uBlock is missing. 
Even upon using the customize toolbar there are no signs of said icon. 
I have tried restarting the browser after installation, uninstalling reinstalling the extension as well as installing the extension to a new profile. In all cases the extension shows in the addons menu but does not appear to be working.

### Your environment

* uBlock Origin version: 1.16.4.30 legacy
* Browser Name and version: Pale Moon 29.4.4
* Operating System and version: Windows 10 Home

**Comment by JustOff** [comment]
I can't reproduce this using a new, unmodified browser profile where  uBlock Origin is the only extension. Please check if everything is ok with Pale Moon portable.

**Comment by dustylancer** [comment]
Tried it with the portable version of Pale Moon, installs and works as it should. Tried again with a new profile of the normal Pale Moon, did not work.

Uninstalled Palemoon completely deleted all the local and roaming folder data, reinstalled and then migrated my main profile back after testing uBlock with a clean install. Both worked. No clue as what caused uBlock to disappear from the previous install in the original profile and new one. Sorry for wasting your time.

**Comment by JustOff** [comment]
I'm glad you worked it out.
