### ISSUE TITLE
i can't install the extension from pale moon

### ISSUE THREAD

**Issue by PhoenixYeager** [gorhill/uBlock-for-firefox-legacy#335]
### Prerequisites

 

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature] hi, i downloaded palemoon and i wanted to install ublock origin but i can't download it since it always remains the loading of the assets and i don't know what to do ... i tried to load the installation page in other browsers it is loading them

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version: palemoon version 31.3.0.0.1 64 bit
* Operating System and version: windows 7 ultimate

**Comment by Gittyperson** [comment]
Most probably a GitHub issue. You need the Palefill extension for GitHub to work properly.

https://martok.github.io/palefill/ (install button on top)

**Comment by PhoenixYeager** [comment]
> Most probably a GitHub issue. You need the Palefill extension for GitHub to work properly.
> 
> https://martok.github.io/palefill/ (install button on top)

i installed the extension you sent me and it works, thanks! i had been in this situation for about two weeks
