### ISSUE TITLE
Can't install in Waterfox G5.1.2

### ISSUE THREAD

**Issue by Chirunos** [gorhill/uBlock-for-firefox-legacy#339]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
I'm unable to install the extension in Waterfox G5.1
![image](https://user-images.githubusercontent.com/85644671/201997664-3af27bb7-3468-4464-bb30-96b3ed722f36.png)
[Description of the bug or feature]

### A specific URL where the issue occurs
N/A
[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step] Open the browser
2. [Second Step] Open the release page
3. [and so on...] Click "uBlock0_1.16.4.30.firefox-legacy.xpi"

### Expected behavior:
The extension installs successfully
[What you expected to happen]

### Actual behavior:
The extension isn't installed successfully
[What actually happened]

### Your environment

* uBlock Origin version: 1.16.4.30
* Browser Name and version: Waterfox G5.1.2
* Operating System and version: openSUSE Leap 15.4 (stable)

**Comment by mapx-** [comment]
Why legacy in g5.1 ? 
Install the current release from:

https://github.com/gorhill/uBlock/releases/tag/1.45.3b1

**Comment by Chirunos** [comment]
I use it as a backup if some **feature** (not filter) doesn't work properly in uBo WebExt

> Why legacy in g5.1 ? Install the current release from:
> 
> https://github.com/gorhill/uBlock/releases/tag/1.45.3b1

**Comment by Poopooracoocoo** [comment]
Can't exactly expect a legacy add-on to be compatible with modern versions of Firefox.

**Comment by Chirunos** [comment]
> Can't exactly expect a legacy add-on to be compatible with modern versions of Firefox.

As far as I'm aware of, Waterfox current does support some legacy extensions. This isn't much of a problem for me and can be considered pointless and redundant

**Comment by krystian3w** [comment]
Possible use these:

https://github.com/xiaoxiaoflood/firefox-scripts/tree/master/extensions

As long as you know what needs to be fixed in the uBo 1.16.x code. By default, it doesn't go to open the dashboard and maybe pop-up from under the icon.
