### ISSUE TITLE
Legacy version not parsing Custom List for PaleMoon Extension

### ISSUE THREAD

**Issue by cspence001** [gorhill/uBlock-for-firefox-legacy#341]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Adding Custom Filter list -  https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/lan-block.txt
Extension does not parse - https://imgur.com/RDcnQuk

### A specific URL where the issue occurs
https://imgur.com/RDcnQuk

### Steps to Reproduce

1. Added Custom Filter List to Extension [ https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/lan-block.txt ]
2. Clicked Apply Changes
3. Clicked Update Now
4. Closed and Re-opened browser

### Expected behavior:
Loaded Custom Filter List

### Actual behavior:
Not Loading/Parsing Filter List
(Works for previously added custom filter lists)

### Your environment
Intel MacOS Ventura 13.1 Running PaleMoon 32.0.0 with UBlock 

* uBlock Origin version:  uBlock Origin v1.16.4.30 
[https://github.com/gorhill/uBlock-for-firefox-legacy/releases/expanded_assets/firefox-legacy-1.16.4.30 ]
* Browser Name and version:  palemoon-32.0.0.mac64.dmg
[ https://forum.palemoon.org/viewtopic.php?f=41&t=29366 ]
* Operating System and version:  MacBook Pro 2.8 GHz Quad-Core Intel Core i7, OS Ventura 13.1

**Comment by ghost** [comment]
IPv6 is not supported? Try removing `[::]`-style filters.

**Comment by cspence001** [comment]
> IPv6 is not supported? Try removing `[::]`-style filters.

@gwarser  That worked! Thanks! 
https://gist.githubusercontent.com/cspence001/a12be6eeae6257d3e04f9e674f8a8655/raw/ac3c937ffe4e7c6f3d52e11fe01f0085452c699b/lan_block.txt
