### ISSUE TITLE
update failed only for ubo-ads list.

### ISSUE THREAD

**Issue by AroKol78** [gorhill/uBlock-for-firefox-legacy#353]
Problem updating the `ubo-ads` list. other lists from `ubo` **no** problem.
I also checked the upstream `ubo-ads` list and there is also a problem.
This problem appeared yesterday, maybe it is because of empty list 2025 (I'm not sure).
![bugupdateubo01](https://github.com/user-attachments/assets/ce9b42aa-e42d-408a-b0a7-bcbaa951c879)

**Comment by ghost** [comment]
Then maybe this will help https://github.com/uBlockOrigin/uAssets/commit/d12303e822161f97b13cf3631af6b4baa2a78a0d

**Comment by AroKol78** [comment]
Thanks a lot, it's ok now.
