### ISSUE TITLE
[Service] Release communication

### ISSUE THREAD

**Issue by JustOff** [gorhill/uBlock-for-firefox-legacy#72]
This issue is intended for release communication.

**Comment by JustOff** [comment]
Please release the next version. Thank you in advance.

**Comment by gorhill** [comment]
I would appreciate if you can fulfill the release notes -- do you have permission to do so?

**Comment by JustOff** [comment]
Yes, of course, I will do this for both `1.16.4.16` & `1.16.4.17`.

~~As a side note, I'm a little confused how [this commit](https://github.com/gorhill/uBlock-for-firefox-legacy/commit/1274c8b38464f7e7e6ca3abf8f1f0980c112488e) got the old version number? It's not difficult for me to update it manually, but I was sure that this would happen automatically during the release process.~~ Oh, I see that you've already fixed it, thanks.

**Comment by JustOff** [comment]
You seem to have changed the name of the xpi package so that [it includes the version number](https://github.com/gorhill/uBlock-for-firefox-legacy/releases/tag/firefox-legacy-1.16.4.17). Was it intentional or just a typo? Can we rename it as it was before, so that the update works?

**Comment by gorhill** [comment]
I forgot about this, I had a modified shell script on my side to include the version number as part of the file just as is done with mainstream uBO. I think I will keep (and commit) those changes as it's useful to have the version as part of the file name when downloading the file.

**Comment by JustOff** [comment]
> I forgot about this, I had a modified shell script on my side to include the version number as part of the file just as is done with mainstream uBO. I think I will keep (and commit) those changes

Ok, and when you push it, I will update [update.template.xml](https://github.com/gorhill/uBlock-for-firefox-legacy/blob/master/dist/update/update.template.xml) to be ready for the next release.

> it's useful to have the version as part of the file name when downloading the file.

I completely agree with this, I always wanted uBO to have it that way.

**Comment by JustOff** [comment]
Thanks, closing till the next release.

**Comment by gorhill** [comment]
I'm un-watching to avoid repeated notifications from isdue tracker, please mention my user id if I am needed.

**Comment by JustOff** [comment]
@gorhill 
Please review the changes and release the next version.
The draft is [here](https://github.com/gorhill/uBlock-for-firefox-legacy/releases/tag/untagged-b474a82d56d6b147d19e), thank you in advance.

**Comment by JustOff** [comment]
Thank you, closing till the next release.

**Comment by JustOff** [comment]
@gorhill 
Please review the changes and release the next version.
The draft is [ready](https://github.com/gorhill/uBlock-for-firefox-legacy/releases/tag/untagged-1352e707a0b449f82e16), thank you in advance.

**Comment by JustOff** [comment]
@gorhill 
Thank you, but it seems you forgot to push `update.xml`.

**Comment by gorhill** [comment]
Sorry about this; fixed.

**Comment by JustOff** [comment]
Thank you, closing till the next release.

**Comment by JustOff** [comment]
@gorhill 
Please review the changes and release `firefox-legacy-1.16.4.20`.
The draft is [ready](https://github.com/gorhill/uBlock-for-firefox-legacy/releases/tag/untagged-972c92f9f7abe7e892ec), thank you in advance.

**Comment by JustOff** [comment]
Thank you.

**Comment by JustOff** [comment]
@gorhill 
Please review the changes and release `firefox-legacy-1.16.4.21`.
The draft is [ready](https://github.com/gorhill/uBlock-for-firefox-legacy/releases/tag/untagged-3e7a2d90da05579e22d3), thank you in advance.

**Comment by JustOff** [comment]
Many thanks!

**Comment by JustOff** [comment]
@gorhill 
Please review the changes and release `firefox-legacy-1.16.4.22`.
The draft is [ready](https://github.com/gorhill/uBlock-for-firefox-legacy/releases/tag/untagged-b4dc687f08a37ed04282), thank you in advance.

**Comment by JustOff** [comment]
Thank you!

**Comment by JustOff** [comment]
@gorhill 
Please review the changes and release `firefox-legacy-1.16.4.23`.
The draft is [ready](https://github.com/gorhill/uBlock-for-firefox-legacy/releases/tag/untagged-1bb0e42b48869c1223dc), thank you in advance.

**Comment by JustOff** [comment]
@gorhill, thank you!

Would you mind if I move `The release notes are created/maintained by @JustOff` note below the changes, as they are obviously more important?

**Comment by gorhill** [comment]
I don't mind, I just want to be sure I am not erroneously credited as having worked to craft the release notes.

**Comment by JustOff** [comment]
Ok, agreed.

**Comment by JustOff** [comment]
@gorhill 
Please review the changes and release `firefox-legacy-1.16.4.24`.
The draft is [ready](https://github.com/gorhill/uBlock-for-firefox-legacy/releases/tag/untagged-656ac5a9498b94a99f4d), thank you in advance.

**Comment by JustOff** [comment]
Thank you.

**Comment by JustOff** [comment]
@gorhill 
Please review the changes and release `firefox-legacy-1.16.4.26`.
The draft is [ready](https://github.com/gorhill/uBlock-for-firefox-legacy/releases/tag/untagged-af7f6c0ec574eaa58777), thank you in advance.

**Comment by gorhill** [comment]
Maybe at this point it's best if you handle the publishing? There is not much value added by having the publishing go through me.

**Comment by JustOff** [comment]
@gorhill 
Initially you reserved the right to release new versions to do code reviews, but if you feel this is no longer required, I can publish myself, of course.

**Comment by gorhill** [comment]
I don't think I need to code review anymore, I trust that all is done properly at this point.

**Comment by JustOff** [comment]
Ok, thank you. I'll try to keep it that way.
