### ISSUE TITLE
Missing feature: No scripting

### ISSUE THREAD

**Issue by THEtomaso** [gorhill/uBlock-for-firefox-legacy#95]
Reference:
https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-scripting

**Comment by JamesTheAwesomeDude** [comment]
I'm going to mention the word "javascript" in this thread so it'll show up when searching issues (it doesn't currently)

This is definitely a really important feature; it's such a wonderful workaround for modal _You're Not A Cookie-Keeper_ pop-ups
